/* peasy.h generated by valac, the Vala compiler, do not modify */


#ifndef __PEASY_H__
#define __PEASY_H__

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <geanyplugin.h>
#include <gdk/gdk.h>

G_BEGIN_DECLS


#define PEASY_TYPE_PLUGIN_CONFIGURE (peasy_plugin_configure_get_type ())
#define PEASY_PLUGIN_CONFIGURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_CONFIGURE, PeasyPluginConfigure))
#define PEASY_IS_PLUGIN_CONFIGURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_CONFIGURE))
#define PEASY_PLUGIN_CONFIGURE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_CONFIGURE, PeasyPluginConfigureIface))

typedef struct _PeasyPluginConfigure PeasyPluginConfigure;
typedef struct _PeasyPluginConfigureIface PeasyPluginConfigureIface;

#define PEASY_TYPE_PLUGIN_HELP (peasy_plugin_help_get_type ())
#define PEASY_PLUGIN_HELP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_HELP, PeasyPluginHelp))
#define PEASY_IS_PLUGIN_HELP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_HELP))
#define PEASY_PLUGIN_HELP_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_HELP, PeasyPluginHelpIface))

typedef struct _PeasyPluginHelp PeasyPluginHelp;
typedef struct _PeasyPluginHelpIface PeasyPluginHelpIface;

#define PEASY_TYPE_OBJECT (peasy_object_get_type ())
#define PEASY_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_OBJECT, PeasyObject))
#define PEASY_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_OBJECT, PeasyObjectClass))
#define PEASY_IS_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_OBJECT))
#define PEASY_IS_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_OBJECT))
#define PEASY_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_OBJECT, PeasyObjectClass))

typedef struct _PeasyObject PeasyObject;
typedef struct _PeasyObjectClass PeasyObjectClass;
typedef struct _PeasyObjectPrivate PeasyObjectPrivate;

#define PEASY_TYPE_PLUGIN_IFACE (peasy_plugin_iface_get_type ())
#define PEASY_PLUGIN_IFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_IFACE, PeasyPluginIface))
#define PEASY_IS_PLUGIN_IFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_IFACE))
#define PEASY_PLUGIN_IFACE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_IFACE, PeasyPluginIfaceIface))

typedef struct _PeasyPluginIface PeasyPluginIface;
typedef struct _PeasyPluginIfaceIface PeasyPluginIfaceIface;

#define PEASY_TYPE_PLUGIN (peasy_plugin_get_type ())
#define PEASY_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN, PeasyPlugin))
#define PEASY_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_PLUGIN, PeasyPluginClass))
#define PEASY_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN))
#define PEASY_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_PLUGIN))
#define PEASY_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_PLUGIN, PeasyPluginClass))

typedef struct _PeasyPlugin PeasyPlugin;
typedef struct _PeasyPluginClass PeasyPluginClass;
typedef struct _PeasyPluginPrivate PeasyPluginPrivate;

#define PEASY_TYPE_KEY_GROUP (peasy_key_group_get_type ())
#define PEASY_KEY_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_KEY_GROUP, PeasyKeyGroup))
#define PEASY_KEY_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_KEY_GROUP, PeasyKeyGroupClass))
#define PEASY_IS_KEY_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_KEY_GROUP))
#define PEASY_IS_KEY_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_KEY_GROUP))
#define PEASY_KEY_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_KEY_GROUP, PeasyKeyGroupClass))

typedef struct _PeasyKeyGroup PeasyKeyGroup;
typedef struct _PeasyKeyGroupClass PeasyKeyGroupClass;

#define PEASY_TYPE_DOCUMENT (peasy_document_get_type ())
#define PEASY_DOCUMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_DOCUMENT, PeasyDocument))
#define PEASY_DOCUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_DOCUMENT, PeasyDocumentClass))
#define PEASY_IS_DOCUMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_DOCUMENT))
#define PEASY_IS_DOCUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_DOCUMENT))
#define PEASY_DOCUMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_DOCUMENT, PeasyDocumentClass))

typedef struct _PeasyDocument PeasyDocument;
typedef struct _PeasyDocumentClass PeasyDocumentClass;
typedef struct _PeasyDocumentPrivate PeasyDocumentPrivate;

#define PEASY_TYPE_EDITOR (peasy_editor_get_type ())
#define PEASY_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_EDITOR, PeasyEditor))
#define PEASY_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_EDITOR, PeasyEditorClass))
#define PEASY_IS_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_EDITOR))
#define PEASY_IS_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_EDITOR))
#define PEASY_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_EDITOR, PeasyEditorClass))

typedef struct _PeasyEditor PeasyEditor;
typedef struct _PeasyEditorClass PeasyEditorClass;

#define PEASY_TYPE_FILETYPE (peasy_filetype_get_type ())
#define PEASY_FILETYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_FILETYPE, PeasyFiletype))
#define PEASY_FILETYPE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_FILETYPE, PeasyFiletypeClass))
#define PEASY_IS_FILETYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_FILETYPE))
#define PEASY_IS_FILETYPE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_FILETYPE))
#define PEASY_FILETYPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_FILETYPE, PeasyFiletypeClass))

typedef struct _PeasyFiletype PeasyFiletype;
typedef struct _PeasyFiletypeClass PeasyFiletypeClass;

#define PEASY_TYPE_INDENT_TYPE (peasy_indent_type_get_type ())
typedef struct _PeasyEditorPrivate PeasyEditorPrivate;

#define PEASY_TYPE_SIGNALS (peasy_signals_get_type ())
#define PEASY_SIGNALS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_SIGNALS, PeasySignals))
#define PEASY_SIGNALS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_SIGNALS, PeasySignalsClass))
#define PEASY_IS_SIGNALS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_SIGNALS))
#define PEASY_IS_SIGNALS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_SIGNALS))
#define PEASY_SIGNALS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_SIGNALS, PeasySignalsClass))

typedef struct _PeasySignals PeasySignals;
typedef struct _PeasySignalsClass PeasySignalsClass;
typedef struct _PeasySignalsPrivate PeasySignalsPrivate;
typedef struct _PeasyFiletypePrivate PeasyFiletypePrivate;

#define PEASY_TYPE_KEY_BINDING (peasy_key_binding_get_type ())
#define PEASY_KEY_BINDING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_KEY_BINDING, PeasyKeyBinding))
#define PEASY_KEY_BINDING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_KEY_BINDING, PeasyKeyBindingClass))
#define PEASY_IS_KEY_BINDING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_KEY_BINDING))
#define PEASY_IS_KEY_BINDING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_KEY_BINDING))
#define PEASY_KEY_BINDING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_KEY_BINDING, PeasyKeyBindingClass))

typedef struct _PeasyKeyBinding PeasyKeyBinding;
typedef struct _PeasyKeyBindingClass PeasyKeyBindingClass;
typedef struct _PeasyKeyBindingPrivate PeasyKeyBindingPrivate;
typedef struct _PeasyKeyGroupPrivate PeasyKeyGroupPrivate;

struct _PeasyPluginConfigureIface {
	GTypeInterface parent_iface;
	GtkWidget* (*configure) (PeasyPluginConfigure* self, GtkDialog* parent);
};

struct _PeasyPluginHelpIface {
	GTypeInterface parent_iface;
	void (*help) (PeasyPluginHelp* self);
};

struct _PeasyObject {
	GObject parent_instance;
	PeasyObjectPrivate * priv;
};

struct _PeasyObjectClass {
	GObjectClass parent_class;
};

struct _PeasyPluginIfaceIface {
	GTypeInterface parent_iface;
};

struct _PeasyPlugin {
	PeasyObject parent_instance;
	PeasyPluginPrivate * priv;
	GeanyPlugin* geany_plugin;
};

struct _PeasyPluginClass {
	PeasyObjectClass parent_class;
	gboolean (*enable) (PeasyPlugin* self);
	void (*disable) (PeasyPlugin* self);
};

struct _PeasyDocument {
	PeasyObject parent_instance;
	PeasyDocumentPrivate * priv;
	GeanyDocument* geany_doc;
	PeasyEditor* editor;
};

struct _PeasyDocumentClass {
	PeasyObjectClass parent_class;
};

typedef enum  {
	PEASY_INDENT_TYPE_TABS = GEANY_INDENT_TYPE_TABS,
	PEASY_INDENT_TYPE_SPACES = GEANY_INDENT_TYPE_SPACES,
	PEASY_INDENT_TYPE_BOTH = GEANY_INDENT_TYPE_BOTH
} PeasyIndentType;

struct _PeasyEditor {
	GObject parent_instance;
	PeasyEditorPrivate * priv;
	GeanyEditor* geany_editor;
	ScintillaObject* sci;
};

struct _PeasyEditorClass {
	GObjectClass parent_class;
};

struct _PeasySignals {
	PeasyObject parent_instance;
	PeasySignalsPrivate * priv;
};

struct _PeasySignalsClass {
	PeasyObjectClass parent_class;
};

struct _PeasyFiletype {
	PeasyObject parent_instance;
	PeasyFiletypePrivate * priv;
	GeanyFiletype* geany_ft;
};

struct _PeasyFiletypeClass {
	PeasyObjectClass parent_class;
};

struct _PeasyKeyBinding {
	GObject parent_instance;
	PeasyKeyBindingPrivate * priv;
	GeanyKeyBinding* geany_binding;
};

struct _PeasyKeyBindingClass {
	GObjectClass parent_class;
	gboolean (*default_handler) (PeasyKeyBinding* self, gint id);
};

struct _PeasyKeyGroup {
	GObject parent_instance;
	PeasyKeyGroupPrivate * priv;
	GeanyKeyGroup* geany_group;
};

struct _PeasyKeyGroupClass {
	GObjectClass parent_class;
	gboolean (*default_handler) (PeasyKeyGroup* self, gint id);
};


const gchar* peasy_get_locale_dir (void);
const gchar* peasy_gettext (const gchar* msgid);
GType peasy_plugin_configure_get_type (void) G_GNUC_CONST;
GtkWidget* peasy_plugin_configure_configure (PeasyPluginConfigure* self, GtkDialog* parent);
GType peasy_plugin_help_get_type (void) G_GNUC_CONST;
void peasy_plugin_help_help (PeasyPluginHelp* self);
GType peasy_object_get_type (void) G_GNUC_CONST;
GType peasy_plugin_iface_get_type (void) G_GNUC_CONST;
GType peasy_plugin_get_type (void) G_GNUC_CONST;
gboolean peasy_plugin_enable (PeasyPlugin* self);
void peasy_plugin_disable (PeasyPlugin* self);
GType peasy_key_group_get_type (void) G_GNUC_CONST;
PeasyKeyGroup* peasy_plugin_add_key_group (PeasyPlugin* self, const gchar* section_name, gsize count);
GType peasy_document_get_type (void) G_GNUC_CONST;
GType peasy_editor_get_type (void) G_GNUC_CONST;
GPtrArray* peasy_document_all_documents (void);
GType peasy_filetype_get_type (void) G_GNUC_CONST;
PeasyDocument* peasy_document_new_from_file (const gchar* locale_filename, gboolean readonly, PeasyFiletype* ft, const gchar* forced_enc);
PeasyDocument* peasy_document_construct_from_file (GType object_type, const gchar* locale_filename, gboolean readonly, PeasyFiletype* ft, const gchar* forced_enc);
PeasyDocument* peasy_document_get_current (void);
gboolean peasy_document_close (PeasyDocument* self);
gboolean peasy_document_save (PeasyDocument* self, gboolean force);
gboolean peasy_document_save_as (PeasyDocument* self, const gchar* file_name);
gboolean peasy_document_reload (PeasyDocument* self, const gchar* forced_enc);
gboolean peasy_document_get_changed (PeasyDocument* self);
void peasy_document_set_changed (PeasyDocument* self, gboolean value);
const gchar* peasy_document_get_encoding (PeasyDocument* self);
void peasy_document_set_encoding (PeasyDocument* self, const gchar* value);
gboolean peasy_document_get_is_valid (PeasyDocument* self);
gboolean peasy_document_get_has_bom (PeasyDocument* self);
gboolean peasy_document_get_has_tags (PeasyDocument* self);
guint peasy_document_get_id (PeasyDocument* self);
gchar* peasy_document_get_display_name (PeasyDocument* self);
GType peasy_indent_type_get_type (void) G_GNUC_CONST;
gchar* peasy_editor_get_word_at (PeasyEditor* self, gint pos, const gchar* wordchars);
gboolean peasy_editor_goto (PeasyEditor* self, gint pos, gboolean mark);
PeasyEditor* peasy_editor_new (void);
PeasyEditor* peasy_editor_construct (GType object_type);
PeasyIndentType peasy_editor_get_indent_type (PeasyEditor* self);
void peasy_editor_set_indent_type (PeasyEditor* self, PeasyIndentType value);
gint peasy_editor_get_indent_width (PeasyEditor* self);
void peasy_editor_set_indent_width (PeasyEditor* self, gint value);
extern GeanyPlugin* peasy_peasy_plugin;
GType peasy_signals_get_type (void) G_GNUC_CONST;
extern PeasySignals* peasy_peasy_signals;
void peasy_static_init (GeanyPlugin* p);
void peasy_object_signal_connect (GObject* obj, const gchar* signal_name, gboolean after, GCallback cb, void* data);
PeasyObject* peasy_object_new (void);
PeasyObject* peasy_object_construct (GType object_type);
PeasySignals* peasy_object_get_plugin_signals (PeasyObject* self);
PeasySignals* peasy_signals_new (void);
PeasySignals* peasy_signals_construct (GType object_type);
GPtrArray* peasy_filetype_all_filetypes (void);
GType peasy_key_binding_get_type (void) G_GNUC_CONST;
gboolean peasy_key_binding_default_handler (PeasyKeyBinding* self, gint id);
gboolean peasy_key_group_default_handler (PeasyKeyGroup* self, gint id);
PeasyKeyBinding* peasy_key_group_add_keybinding (PeasyKeyGroup* self, const gchar* name, const gchar* label, GtkMenuItem* menu_item, gint def_key, GdkModifierType def_mod);
PeasyKeyBinding* peasy_key_group_add_keybinding_with_id (PeasyKeyGroup* self, const gchar* name, const gchar* label, GtkMenuItem* menu_item, gint def_key, GdkModifierType def_mod, gint id);
PeasyKeyBinding* peasy_key_group_get_item (PeasyKeyGroup* self, gint id);
PeasyKeyGroup* peasy_key_group_new (void);
PeasyKeyGroup* peasy_key_group_construct (GType object_type);


G_END_DECLS

#endif
