/* plugin.c generated by valac, the Vala compiler
 * generated from plugin.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libpeas/peas.h>
#include <gtk/gtk.h>
#include <geanyplugin.h>

#define _g_free0(var) (var = (g_free (var), NULL))

#define PEASY_TYPE_PLUGIN_CONFIGURE (peasy_plugin_configure_get_type ())
#define PEASY_PLUGIN_CONFIGURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_CONFIGURE, PeasyPluginConfigure))
#define PEASY_IS_PLUGIN_CONFIGURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_CONFIGURE))
#define PEASY_PLUGIN_CONFIGURE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_CONFIGURE, PeasyPluginConfigureIface))

typedef struct _PeasyPluginConfigure PeasyPluginConfigure;
typedef struct _PeasyPluginConfigureIface PeasyPluginConfigureIface;

#define PEASY_TYPE_PLUGIN_HELP (peasy_plugin_help_get_type ())
#define PEASY_PLUGIN_HELP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_HELP, PeasyPluginHelp))
#define PEASY_IS_PLUGIN_HELP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_HELP))
#define PEASY_PLUGIN_HELP_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_HELP, PeasyPluginHelpIface))

typedef struct _PeasyPluginHelp PeasyPluginHelp;
typedef struct _PeasyPluginHelpIface PeasyPluginHelpIface;

#define PEASY_TYPE_OBJECT (peasy_object_get_type ())
#define PEASY_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_OBJECT, PeasyObject))
#define PEASY_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_OBJECT, PeasyObjectClass))
#define PEASY_IS_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_OBJECT))
#define PEASY_IS_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_OBJECT))
#define PEASY_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_OBJECT, PeasyObjectClass))

typedef struct _PeasyObject PeasyObject;
typedef struct _PeasyObjectClass PeasyObjectClass;
typedef struct _PeasyObjectPrivate PeasyObjectPrivate;

#define PEASY_TYPE_PLUGIN_IFACE (peasy_plugin_iface_get_type ())
#define PEASY_PLUGIN_IFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_IFACE, PeasyPluginIface))
#define PEASY_IS_PLUGIN_IFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_IFACE))
#define PEASY_PLUGIN_IFACE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_IFACE, PeasyPluginIfaceIface))

typedef struct _PeasyPluginIface PeasyPluginIface;
typedef struct _PeasyPluginIfaceIface PeasyPluginIfaceIface;

#define PEASY_TYPE_PLUGIN (peasy_plugin_get_type ())
#define PEASY_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN, PeasyPlugin))
#define PEASY_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_PLUGIN, PeasyPluginClass))
#define PEASY_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN))
#define PEASY_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_PLUGIN))
#define PEASY_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_PLUGIN, PeasyPluginClass))

typedef struct _PeasyPlugin PeasyPlugin;
typedef struct _PeasyPluginClass PeasyPluginClass;
typedef struct _PeasyPluginPrivate PeasyPluginPrivate;

#define PEASY_TYPE_KEY_GROUP (peasy_key_group_get_type ())
#define PEASY_KEY_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_KEY_GROUP, PeasyKeyGroup))
#define PEASY_KEY_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_KEY_GROUP, PeasyKeyGroupClass))
#define PEASY_IS_KEY_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_KEY_GROUP))
#define PEASY_IS_KEY_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_KEY_GROUP))
#define PEASY_KEY_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_KEY_GROUP, PeasyKeyGroupClass))

typedef struct _PeasyKeyGroup PeasyKeyGroup;
typedef struct _PeasyKeyGroupClass PeasyKeyGroupClass;

struct _PeasyPluginConfigureIface {
	GTypeInterface parent_iface;
	GtkWidget* (*configure) (PeasyPluginConfigure* self, GtkDialog* parent);
};

struct _PeasyPluginHelpIface {
	GTypeInterface parent_iface;
	void (*help) (PeasyPluginHelp* self);
};

struct _PeasyObject {
	GObject parent_instance;
	PeasyObjectPrivate * priv;
};

struct _PeasyObjectClass {
	GObjectClass parent_class;
};

struct _PeasyPluginIfaceIface {
	GTypeInterface parent_iface;
};

struct _PeasyPlugin {
	PeasyObject parent_instance;
	PeasyPluginPrivate * priv;
	GeanyPlugin* geany_plugin;
};

struct _PeasyPluginClass {
	PeasyObjectClass parent_class;
	gboolean (*enable) (PeasyPlugin* self);
	void (*disable) (PeasyPlugin* self);
};


extern GHashTable* peasy_native_abis;
GHashTable* peasy_native_abis = NULL;
static gpointer peasy_plugin_parent_class = NULL;
static PeasyPluginIfaceIface* peasy_plugin_peasy_plugin_iface_parent_iface = NULL;

const gchar* peasy_get_locale_dir (void);
const gchar* peasy_gettext (const gchar* msgid);
gboolean peasy_do_check_abi (gint abi);
gboolean peasy_check_abi (PeasObjectModule* mod, gint abi_ver);
GType peasy_plugin_configure_get_type (void) G_GNUC_CONST;
GtkWidget* peasy_plugin_configure_configure (PeasyPluginConfigure* self, GtkDialog* parent);
GType peasy_plugin_help_get_type (void) G_GNUC_CONST;
void peasy_plugin_help_help (PeasyPluginHelp* self);
GType peasy_object_get_type (void) G_GNUC_CONST;
GType peasy_plugin_iface_get_type (void) G_GNUC_CONST;
GType peasy_plugin_get_type (void) G_GNUC_CONST;
enum  {
	PEASY_PLUGIN_DUMMY_PROPERTY
};
gboolean peasy_plugin_enable (PeasyPlugin* self);
static gboolean peasy_plugin_real_enable (PeasyPlugin* self);
void peasy_plugin_disable (PeasyPlugin* self);
static void peasy_plugin_real_disable (PeasyPlugin* self);
static PeasyPlugin* peasy_plugin_construct (GType object_type);
PeasyObject* peasy_object_new (void);
PeasyObject* peasy_object_construct (GType object_type);
GType peasy_key_group_get_type (void) G_GNUC_CONST;
PeasyKeyGroup* peasy_plugin_add_key_group (PeasyPlugin* self, const gchar* section_name, gsize count);
PeasyKeyGroup* peasy_key_group_new_from_geany (GeanyKeyGroup* kb_group);
PeasyKeyGroup* peasy_key_group_construct_from_geany (GType object_type, GeanyKeyGroup* kb_group);
static void peasy_plugin_finalize (GObject* obj);


/**
 * Function that native plugins must call in their peas_register_types().
 *
 * @param mod The ObjectModule passed to peas_register_types() by libpeas
 * @param abi_ver The ABI version the plugin was compiled against,
 *                 simple pass GEANY_API_VERSION.
 *
 * @return true if the ABI check has passed, false otherwise. Do not
 *          proceed calling peas_object_module_register_extension_type()
 *          on false.
 */
gboolean peasy_check_abi (PeasObjectModule* mod, gint abi_ver) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (mod != NULL, FALSE);
	_tmp0_ = abi_ver;
	_tmp1_ = peasy_do_check_abi (_tmp0_);
	if (!_tmp1_) {
		GHashTable* _tmp2_ = NULL;
		PeasObjectModule* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		_tmp2_ = peasy_native_abis;
		_tmp3_ = mod;
		g_object_get (_tmp3_, "module-name", &_tmp4_, NULL);
		_tmp5_ = _tmp4_;
		_tmp6_ = _tmp5_;
		_tmp7_ = g_strdup (_tmp6_);
		_tmp8_ = abi_ver;
		g_hash_table_replace (_tmp2_, _tmp7_, (gpointer) ((gintptr) _tmp8_));
		_g_free0 (_tmp6_);
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


GtkWidget* peasy_plugin_configure_configure (PeasyPluginConfigure* self, GtkDialog* parent) {
	g_return_val_if_fail (self != NULL, NULL);
	return PEASY_PLUGIN_CONFIGURE_GET_INTERFACE (self)->configure (self, parent);
}


static void peasy_plugin_configure_base_init (PeasyPluginConfigureIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType peasy_plugin_configure_get_type (void) {
	static volatile gsize peasy_plugin_configure_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_configure_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginConfigureIface), (GBaseInitFunc) peasy_plugin_configure_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType peasy_plugin_configure_type_id;
		peasy_plugin_configure_type_id = g_type_register_static (G_TYPE_INTERFACE, "PeasyPluginConfigure", &g_define_type_info, 0);
		g_once_init_leave (&peasy_plugin_configure_type_id__volatile, peasy_plugin_configure_type_id);
	}
	return peasy_plugin_configure_type_id__volatile;
}


void peasy_plugin_help_help (PeasyPluginHelp* self) {
	g_return_if_fail (self != NULL);
	PEASY_PLUGIN_HELP_GET_INTERFACE (self)->help (self);
}


static void peasy_plugin_help_base_init (PeasyPluginHelpIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType peasy_plugin_help_get_type (void) {
	static volatile gsize peasy_plugin_help_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_help_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginHelpIface), (GBaseInitFunc) peasy_plugin_help_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType peasy_plugin_help_type_id;
		peasy_plugin_help_type_id = g_type_register_static (G_TYPE_INTERFACE, "PeasyPluginHelp", &g_define_type_info, 0);
		g_once_init_leave (&peasy_plugin_help_type_id__volatile, peasy_plugin_help_type_id);
	}
	return peasy_plugin_help_type_id__volatile;
}


static gboolean peasy_plugin_real_enable (PeasyPlugin* self) {
	g_critical ("Type `%s' does not implement abstract method `peasy_plugin_enable'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return FALSE;
}


gboolean peasy_plugin_enable (PeasyPlugin* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return PEASY_PLUGIN_GET_CLASS (self)->enable (self);
}


static void peasy_plugin_real_disable (PeasyPlugin* self) {
	g_critical ("Type `%s' does not implement abstract method `peasy_plugin_disable'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void peasy_plugin_disable (PeasyPlugin* self) {
	g_return_if_fail (self != NULL);
	PEASY_PLUGIN_GET_CLASS (self)->disable (self);
}


static PeasyPlugin* peasy_plugin_construct (GType object_type) {
	PeasyPlugin * self = NULL;
	self = (PeasyPlugin*) peasy_object_construct (object_type);
	return self;
}


PeasyKeyGroup* peasy_plugin_add_key_group (PeasyPlugin* self, const gchar* section_name, gsize count) {
	PeasyKeyGroup* result = NULL;
	GeanyKeyGroup* kb_group = NULL;
	GeanyPlugin* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gsize _tmp2_ = 0UL;
	GeanyKeyGroup* _tmp3_ = NULL;
	PeasyKeyGroup* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (section_name != NULL, NULL);
	_tmp0_ = self->geany_plugin;
	_tmp1_ = section_name;
	_tmp2_ = count;
	_tmp3_ = plugin_set_key_group_full (_tmp0_, _tmp1_, _tmp2_, NULL, NULL, NULL);
	kb_group = _tmp3_;
	g_return_val_if_fail (kb_group != NULL, NULL);
	_tmp4_ = peasy_key_group_new_from_geany (kb_group);
	result = _tmp4_;
	return result;
}


static void peasy_plugin_class_init (PeasyPluginClass * klass) {
	peasy_plugin_parent_class = g_type_class_peek_parent (klass);
	((PeasyPluginClass *) klass)->enable = peasy_plugin_real_enable;
	((PeasyPluginClass *) klass)->disable = peasy_plugin_real_disable;
	G_OBJECT_CLASS (klass)->finalize = peasy_plugin_finalize;
}


static void peasy_plugin_peasy_plugin_iface_interface_init (PeasyPluginIfaceIface * iface) {
	peasy_plugin_peasy_plugin_iface_parent_iface = g_type_interface_peek_parent (iface);
}


static void peasy_plugin_instance_init (PeasyPlugin * self) {
}


static void peasy_plugin_finalize (GObject* obj) {
	PeasyPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_PLUGIN, PeasyPlugin);
	G_OBJECT_CLASS (peasy_plugin_parent_class)->finalize (obj);
}


GType peasy_plugin_get_type (void) {
	static volatile gsize peasy_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyPlugin), 0, (GInstanceInitFunc) peasy_plugin_instance_init, NULL };
		static const GInterfaceInfo peasy_plugin_iface_info = { (GInterfaceInitFunc) peasy_plugin_peasy_plugin_iface_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType peasy_plugin_type_id;
		peasy_plugin_type_id = g_type_register_static (PEASY_TYPE_OBJECT, "PeasyPlugin", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_type_add_interface_static (peasy_plugin_type_id, PEASY_TYPE_PLUGIN_IFACE, &peasy_plugin_iface_info);
		g_once_init_leave (&peasy_plugin_type_id__volatile, peasy_plugin_type_id);
	}
	return peasy_plugin_type_id__volatile;
}


static void peasy_plugin_iface_base_init (PeasyPluginIfaceIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType peasy_plugin_iface_get_type (void) {
	static volatile gsize peasy_plugin_iface_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_iface_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginIfaceIface), (GBaseInitFunc) peasy_plugin_iface_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType peasy_plugin_iface_type_id;
		peasy_plugin_iface_type_id = g_type_register_static (G_TYPE_INTERFACE, "PeasyPluginIface", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (peasy_plugin_iface_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&peasy_plugin_iface_type_id__volatile, peasy_plugin_iface_type_id);
	}
	return peasy_plugin_iface_type_id__volatile;
}



