/* tags.c generated by valac, the Vala compiler
 * generated from tags.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <geanyplugin.h>


#define PEASY_TYPE_TAG_QUERY (peasy_tag_query_get_type ())
#define PEASY_TAG_QUERY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_TAG_QUERY, PeasyTagQuery))
#define PEASY_TAG_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_TAG_QUERY, PeasyTagQueryClass))
#define PEASY_IS_TAG_QUERY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_TAG_QUERY))
#define PEASY_IS_TAG_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_TAG_QUERY))
#define PEASY_TAG_QUERY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_TAG_QUERY, PeasyTagQueryClass))

typedef struct _PeasyTagQuery PeasyTagQuery;
typedef struct _PeasyTagQueryClass PeasyTagQueryClass;
typedef struct _PeasyTagQueryPrivate PeasyTagQueryPrivate;

#define PEASY_TAG_QUERY_TYPE_SOURCE (peasy_tag_query_source_get_type ())
#define __g_list_free__g_string_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_string_free0_ (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))

struct _PeasyTagQuery {
	GObject parent_instance;
	PeasyTagQueryPrivate * priv;
};

struct _PeasyTagQueryClass {
	GObjectClass parent_class;
};

struct _PeasyTagQueryPrivate {
	gint data_sources;
	GList* names;
};

typedef enum  {
	PEASY_TAG_QUERY_SOURCE_GLOBAL_TAGS,
	PEASY_TAG_QUERY_SOURCE_SESSION_TAGS
} PeasyTagQuerySource;


static gpointer peasy_tag_query_parent_class = NULL;
extern GeanyPlugin* peasy_peasy_plugin;

GType peasy_tag_query_get_type (void) G_GNUC_CONST;
#define PEASY_TAG_QUERY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), PEASY_TYPE_TAG_QUERY, PeasyTagQueryPrivate))
enum  {
	PEASY_TAG_QUERY_DUMMY_PROPERTY
};
GType peasy_tag_query_source_get_type (void) G_GNUC_CONST;
static void _g_string_free0_ (gpointer var);
static void _g_list_free__g_string_free0_ (GList* self);
PeasyTagQuery* peasy_tag_query_new_with_source (PeasyTagQuerySource source);
PeasyTagQuery* peasy_tag_query_construct_with_source (GType object_type, PeasyTagQuerySource source);
gint peasy_tag_query_match_name (PeasyTagQuery* self, const gchar* name, gint len);
static gint peasy_tag_query_compare_fn (void* _key, void* _tag);
static GPtrArray* peasy_tag_query_get_tags_by_name (PeasyTagQuery* self);
static gint _peasy_tag_query_compare_fn___compar_fn_t (void* key1, void* key2);
static GPtrArray* peasy_tag_query_get_all_tags (PeasyTagQuery* self);
GPtrArray* peasy_tag_query_exec (PeasyTagQuery* self);
PeasyTagQuery* peasy_tag_query_new (void);
PeasyTagQuery* peasy_tag_query_construct (GType object_type);
static void peasy_tag_query_finalize (GObject* obj);


GType peasy_tag_query_source_get_type (void) {
	static volatile gsize peasy_tag_query_source_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_tag_query_source_type_id__volatile)) {
		static const GEnumValue values[] = {{PEASY_TAG_QUERY_SOURCE_GLOBAL_TAGS, "PEASY_TAG_QUERY_SOURCE_GLOBAL_TAGS", "global-tags"}, {PEASY_TAG_QUERY_SOURCE_SESSION_TAGS, "PEASY_TAG_QUERY_SOURCE_SESSION_TAGS", "session-tags"}, {0, NULL, NULL}};
		GType peasy_tag_query_source_type_id;
		peasy_tag_query_source_type_id = g_enum_register_static ("PeasyTagQuerySource", values);
		g_once_init_leave (&peasy_tag_query_source_type_id__volatile, peasy_tag_query_source_type_id);
	}
	return peasy_tag_query_source_type_id__volatile;
}


static void _g_string_free0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL));
}


static void _g_list_free__g_string_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_string_free0_, NULL);
	g_list_free (self);
}


PeasyTagQuery* peasy_tag_query_construct_with_source (GType object_type, PeasyTagQuerySource source) {
	PeasyTagQuery * self = NULL;
	PeasyTagQuerySource _tmp0_ = 0;
	self = (PeasyTagQuery*) g_object_new (object_type, NULL);
	_tmp0_ = source;
	self->priv->data_sources = (gint) _tmp0_;
	return self;
}


PeasyTagQuery* peasy_tag_query_new_with_source (PeasyTagQuerySource source) {
	return peasy_tag_query_construct_with_source (PEASY_TYPE_TAG_QUERY, source);
}


gint peasy_tag_query_match_name (PeasyTagQuery* self, const gchar* name, gint len) {
	gint result = 0;
	GString* gstr = NULL;
	GString* _tmp0_ = NULL;
	GString* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GString* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (name != NULL, 0);
	_tmp0_ = g_string_new ("");
	gstr = _tmp0_;
	_tmp1_ = gstr;
	_tmp2_ = name;
	_tmp3_ = len;
	g_string_append_len (_tmp1_, _tmp2_, (gssize) _tmp3_);
	_tmp4_ = gstr;
	gstr = NULL;
	self->priv->names = g_list_append (self->priv->names, _tmp4_);
	result = 0;
	_g_string_free0 (gstr);
	return result;
}


static gint peasy_tag_query_compare_fn (void* _key, void* _tag) {
	gint result = 0;
	GString* key = NULL;
	void* _tmp0_ = NULL;
	TMTag* tag = NULL;
	void* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gssize _tmp4_ = 0L;
	gint _tmp5_ = 0;
	_tmp0_ = _key;
	key = (GString*) _tmp0_;
	_tmp1_ = _tag;
	tag = *((TMTag**) _tmp1_);
	_tmp2_ = key->str;
	_tmp3_ = tag->name;
	_tmp4_ = key->len;
	_tmp5_ = strncmp (_tmp2_, _tmp3_, (gsize) _tmp4_);
	result = _tmp5_;
	return result;
}


static gpointer _g_ptr_array_ref0 (gpointer self) {
	return self ? g_ptr_array_ref (self) : NULL;
}


static gint g_ptr_array_get_length (GPtrArray* self) {
	gint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->len;
	result = (gint) _tmp0_;
	return result;
}


static void g_ptr_array_set_length (GPtrArray* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	g_ptr_array_set_size (self, _tmp0_);
}


static gint _peasy_tag_query_compare_fn___compar_fn_t (void* key1, void* key2) {
	gint result;
	result = peasy_tag_query_compare_fn (key1, key2);
	return result;
}


static GPtrArray* peasy_tag_query_get_tags_by_name (PeasyTagQuery* self) {
	GPtrArray* result = NULL;
	GPtrArray* ret = NULL;
	GPtrArray* _tmp0_ = NULL;
	GString* key = NULL;
	GPtrArray* tags = NULL;
	GeanyPlugin* _tmp1_ = NULL;
	GeanyData* _tmp2_ = NULL;
	GeanyApp* _tmp3_ = NULL;
	TMWorkspace* _tmp4_ = NULL;
	GPtrArray* _tmp5_ = NULL;
	GPtrArray* _tmp6_ = NULL;
	TMTag** match = NULL;
	TMTag** first = NULL;
	TMTag** last = NULL;
	TMTag* tag = NULL;
	GList* _tmp7_ = NULL;
	gconstpointer _tmp8_ = NULL;
	GString* _tmp9_ = NULL;
	GPtrArray* _tmp10_ = NULL;
	gpointer* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	GPtrArray* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	void* _tmp15_ = NULL;
	TMTag** _tmp16_ = NULL;
	TMTag** _tmp17_ = NULL;
	TMTag** _tmp31_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_ptr_array_new_full ((guint) 0, NULL);
	ret = _tmp0_;
	_tmp1_ = peasy_peasy_plugin;
	_tmp2_ = _tmp1_->geany_data;
	_tmp3_ = _tmp2_->app;
	_tmp4_ = _tmp3_->tm_workspace;
	_tmp5_ = _tmp4_->tags_array;
	_tmp6_ = _g_ptr_array_ref0 (_tmp5_);
	tags = _tmp6_;
	_tmp7_ = self->priv->names;
	_tmp8_ = g_list_nth_data (_tmp7_, (guint) 0);
	key = (GString*) _tmp8_;
	_tmp9_ = key;
	_tmp10_ = tags;
	_tmp11_ = _tmp10_->pdata;
	_tmp11__length1 = (gint) _tmp10_->len;
	_tmp12_ = tags;
	_tmp13_ = g_ptr_array_get_length (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = bsearch (_tmp9_, _tmp11_, (gsize) _tmp14_, (gsize) sizeof (TMTag*), _peasy_tag_query_compare_fn___compar_fn_t);
	match = (TMTag**) _tmp15_;
	_tmp16_ = match;
	if (_tmp16_ == NULL) {
		result = ret;
		_g_ptr_array_unref0 (tags);
		return result;
	}
	_tmp17_ = match;
	first = _tmp17_;
	while (TRUE) {
		TMTag** _tmp18_ = NULL;
		GPtrArray* _tmp19_ = NULL;
		gpointer* _tmp20_ = NULL;
		gint _tmp20__length1 = 0;
		gconstpointer _tmp21_ = NULL;
		TMTag** _tmp22_ = NULL;
		GString* _tmp23_ = NULL;
		const gchar* _tmp24_ = NULL;
		TMTag* _tmp25_ = NULL;
		const gchar* _tmp26_ = NULL;
		GString* _tmp27_ = NULL;
		gssize _tmp28_ = 0L;
		gint _tmp29_ = 0;
		TMTag** _tmp30_ = NULL;
		_tmp18_ = first;
		_tmp19_ = tags;
		_tmp20_ = _tmp19_->pdata;
		_tmp20__length1 = (gint) _tmp19_->len;
		_tmp21_ = _tmp20_[0];
		if (!((*_tmp18_) != _tmp21_)) {
			break;
		}
		_tmp22_ = first;
		tag = *(_tmp22_ - 1);
		_tmp23_ = key;
		_tmp24_ = _tmp23_->str;
		_tmp25_ = tag;
		_tmp26_ = _tmp25_->name;
		_tmp27_ = key;
		_tmp28_ = _tmp27_->len;
		_tmp29_ = strncmp (_tmp24_, _tmp26_, (gsize) _tmp28_);
		if (_tmp29_ != 0) {
			break;
		}
		_tmp30_ = first;
		first = _tmp30_ - 1;
	}
	_tmp31_ = match;
	last = _tmp31_;
	while (TRUE) {
		TMTag** _tmp32_ = NULL;
		GPtrArray* _tmp33_ = NULL;
		gpointer* _tmp34_ = NULL;
		gint _tmp34__length1 = 0;
		GPtrArray* _tmp35_ = NULL;
		gint _tmp36_ = 0;
		gint _tmp37_ = 0;
		gconstpointer _tmp38_ = NULL;
		TMTag** _tmp39_ = NULL;
		GString* _tmp40_ = NULL;
		const gchar* _tmp41_ = NULL;
		TMTag* _tmp42_ = NULL;
		const gchar* _tmp43_ = NULL;
		GString* _tmp44_ = NULL;
		gssize _tmp45_ = 0L;
		gint _tmp46_ = 0;
		TMTag** _tmp47_ = NULL;
		_tmp32_ = last;
		_tmp33_ = tags;
		_tmp34_ = _tmp33_->pdata;
		_tmp34__length1 = (gint) _tmp33_->len;
		_tmp35_ = tags;
		_tmp36_ = g_ptr_array_get_length (_tmp35_);
		_tmp37_ = _tmp36_;
		_tmp38_ = _tmp34_[_tmp37_ - 1];
		if (!((*_tmp32_) != _tmp38_)) {
			break;
		}
		_tmp39_ = last;
		tag = *_tmp39_;
		_tmp40_ = key;
		_tmp41_ = _tmp40_->str;
		_tmp42_ = tag;
		_tmp43_ = _tmp42_->name;
		_tmp44_ = key;
		_tmp45_ = _tmp44_->len;
		_tmp46_ = strncmp (_tmp41_, _tmp43_, (gsize) _tmp45_);
		if (_tmp46_ != 0) {
			break;
		}
		_tmp47_ = last;
		last = _tmp47_ + 1;
	}
	{
		TMTag** _tmp48_ = NULL;
		gboolean _tmp49_ = FALSE;
		_tmp48_ = first;
		first = _tmp48_ + 1;
		tag = *_tmp48_;
		_tmp49_ = TRUE;
		while (TRUE) {
			TMTag* _tmp51_ = NULL;
			TMTag** _tmp52_ = NULL;
			GPtrArray* _tmp53_ = NULL;
			TMTag* _tmp54_ = NULL;
			if (!_tmp49_) {
				TMTag** _tmp50_ = NULL;
				_tmp50_ = first;
				first = _tmp50_ + 1;
				tag = *_tmp50_;
			}
			_tmp49_ = FALSE;
			_tmp51_ = tag;
			_tmp52_ = last;
			if (!(_tmp51_ != (*_tmp52_))) {
				break;
			}
			_tmp53_ = ret;
			_tmp54_ = tag;
			g_ptr_array_add (_tmp53_, _tmp54_);
		}
	}
	result = ret;
	_g_ptr_array_unref0 (tags);
	return result;
}


static GPtrArray* peasy_tag_query_get_all_tags (PeasyTagQuery* self) {
	GPtrArray* result = NULL;
	GPtrArray* all_tags = NULL;
	GeanyPlugin* _tmp0_ = NULL;
	GeanyData* _tmp1_ = NULL;
	GeanyApp* _tmp2_ = NULL;
	TMWorkspace* _tmp3_ = NULL;
	GPtrArray* _tmp4_ = NULL;
	GPtrArray* _tmp5_ = NULL;
	GPtrArray* ret = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	GPtrArray* _tmp8_ = NULL;
	gpointer* _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	gpointer* _tmp10_ = NULL;
	gint _tmp10__length1 = 0;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = peasy_peasy_plugin;
	_tmp1_ = _tmp0_->geany_data;
	_tmp2_ = _tmp1_->app;
	_tmp3_ = _tmp2_->tm_workspace;
	_tmp4_ = _tmp3_->tags_array;
	_tmp5_ = _g_ptr_array_ref0 (_tmp4_);
	all_tags = _tmp5_;
	_tmp6_ = g_ptr_array_get_length (all_tags);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_ptr_array_new_full ((guint) _tmp7_, NULL);
	ret = _tmp8_;
	_tmp9_ = ret->pdata;
	_tmp9__length1 = (gint) ret->len;
	_tmp10_ = all_tags->pdata;
	_tmp10__length1 = (gint) all_tags->len;
	_tmp11_ = g_ptr_array_get_length (all_tags);
	_tmp12_ = _tmp11_;
	memcpy (_tmp9_, _tmp10_, (gsize) (_tmp12_ * sizeof (TMTag*)));
	result = ret;
	_g_ptr_array_unref0 (all_tags);
	return result;
}


GPtrArray* peasy_tag_query_exec (PeasyTagQuery* self) {
	GPtrArray* result = NULL;
	GList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->names;
	if (_tmp0_ == NULL) {
		GPtrArray* _tmp1_ = NULL;
		_tmp1_ = peasy_tag_query_get_all_tags (self);
		result = _tmp1_;
		return result;
	} else {
		GPtrArray* _tmp2_ = NULL;
		_tmp2_ = peasy_tag_query_get_tags_by_name (self);
		result = _tmp2_;
		return result;
	}
}


PeasyTagQuery* peasy_tag_query_construct (GType object_type) {
	PeasyTagQuery * self = NULL;
	self = (PeasyTagQuery*) g_object_new (object_type, NULL);
	return self;
}


PeasyTagQuery* peasy_tag_query_new (void) {
	return peasy_tag_query_construct (PEASY_TYPE_TAG_QUERY);
}


static void peasy_tag_query_class_init (PeasyTagQueryClass * klass) {
	peasy_tag_query_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PeasyTagQueryPrivate));
	G_OBJECT_CLASS (klass)->finalize = peasy_tag_query_finalize;
}


static void peasy_tag_query_instance_init (PeasyTagQuery * self) {
	self->priv = PEASY_TAG_QUERY_GET_PRIVATE (self);
}


static void peasy_tag_query_finalize (GObject* obj) {
	PeasyTagQuery * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_TAG_QUERY, PeasyTagQuery);
	__g_list_free__g_string_free0_0 (self->priv->names);
	G_OBJECT_CLASS (peasy_tag_query_parent_class)->finalize (obj);
}


GType peasy_tag_query_get_type (void) {
	static volatile gsize peasy_tag_query_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_tag_query_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyTagQueryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_tag_query_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyTagQuery), 0, (GInstanceInitFunc) peasy_tag_query_instance_init, NULL };
		GType peasy_tag_query_type_id;
		peasy_tag_query_type_id = g_type_register_static (G_TYPE_OBJECT, "PeasyTagQuery", &g_define_type_info, 0);
		g_once_init_leave (&peasy_tag_query_type_id__volatile, peasy_tag_query_type_id);
	}
	return peasy_tag_query_type_id__volatile;
}



