/* data.c generated by valac, the Vala compiler
 * generated from data.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <geanyplugin.h>
#include <gtk/gtk.h>


#define PEASY_TYPE_OBJECT (peasy_object_get_type ())
#define PEASY_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_OBJECT, PeasyObject))
#define PEASY_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_OBJECT, PeasyObjectClass))
#define PEASY_IS_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_OBJECT))
#define PEASY_IS_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_OBJECT))
#define PEASY_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_OBJECT, PeasyObjectClass))

typedef struct _PeasyObject PeasyObject;
typedef struct _PeasyObjectClass PeasyObjectClass;
typedef struct _PeasyObjectPrivate PeasyObjectPrivate;

#define PEASY_TYPE_APP (peasy_app_get_type ())
#define PEASY_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_APP, PeasyApp))
#define PEASY_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_APP, PeasyAppClass))
#define PEASY_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_APP))
#define PEASY_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_APP))
#define PEASY_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_APP, PeasyAppClass))

typedef struct _PeasyApp PeasyApp;
typedef struct _PeasyAppClass PeasyAppClass;
typedef struct _PeasyAppPrivate PeasyAppPrivate;

#define PEASY_TYPE_UI_WIDGETS (peasy_ui_widgets_get_type ())
#define PEASY_UI_WIDGETS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_UI_WIDGETS, PeasyUiWidgets))
#define PEASY_UI_WIDGETS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_UI_WIDGETS, PeasyUiWidgetsClass))
#define PEASY_IS_UI_WIDGETS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_UI_WIDGETS))
#define PEASY_IS_UI_WIDGETS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_UI_WIDGETS))
#define PEASY_UI_WIDGETS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_UI_WIDGETS, PeasyUiWidgetsClass))

typedef struct _PeasyUiWidgets PeasyUiWidgets;
typedef struct _PeasyUiWidgetsClass PeasyUiWidgetsClass;
typedef struct _PeasyUiWidgetsPrivate PeasyUiWidgetsPrivate;

#define PEASY_TYPE_DATA (peasy_data_get_type ())
#define PEASY_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_DATA, PeasyData))
#define PEASY_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_DATA, PeasyDataClass))
#define PEASY_IS_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_DATA))
#define PEASY_IS_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_DATA))
#define PEASY_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_DATA, PeasyDataClass))

typedef struct _PeasyData PeasyData;
typedef struct _PeasyDataClass PeasyDataClass;
typedef struct _PeasyDataPrivate PeasyDataPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _PeasyObject {
	GObject parent_instance;
	PeasyObjectPrivate * priv;
};

struct _PeasyObjectClass {
	GObjectClass parent_class;
};

struct _PeasyApp {
	PeasyObject parent_instance;
	PeasyAppPrivate * priv;
	gboolean debug_mode;
	const gchar* configdir;
	const gchar* datadir;
	const gchar* docdir;
};

struct _PeasyAppClass {
	PeasyObjectClass parent_class;
};

struct _PeasyUiWidgets {
	PeasyObject parent_instance;
	PeasyUiWidgetsPrivate * priv;
	GtkWidget* window;
	GtkWidget* toolbar;
	GtkWidget* sidebar_notebook;
	GtkWidget* notebook;
	GtkWidget* editor_menu;
	GtkWidget* tools_menu;
	GtkWidget* progressbar;
	GtkWidget* message_window_notebook;
	GtkWidget* project_menu;
};

struct _PeasyUiWidgetsClass {
	PeasyObjectClass parent_class;
};

struct _PeasyData {
	PeasyObject parent_instance;
	PeasyDataPrivate * priv;
	PeasyUiWidgets* widgets;
	PeasyApp* app;
	GeanyPrefs* prefs;
	GeanyInterfacePrefs* interface_prefs;
	GeanyToolPrefs* tool_prefs;
	GeanyToolbarPrefs* toolbar_prefs;
	GeanyEditorPrefs* editor_prefs;
	GeanyFilePrefs* file_prefs;
	GeanySearchPrefs* search_prefs;
	GeanyTemplatePrefs* template_prefs;
	GeanyBuildInfo* build_info;
};

struct _PeasyDataClass {
	PeasyObjectClass parent_class;
};


static gpointer peasy_app_parent_class = NULL;
extern GeanyPlugin* peasy_peasy_plugin;
static gpointer peasy_ui_widgets_parent_class = NULL;
static gpointer peasy_data_parent_class = NULL;
static PeasyData* peasy_data__instance;
static PeasyData* peasy_data__instance = NULL;

GType peasy_object_get_type (void) G_GNUC_CONST;
GType peasy_app_get_type (void) G_GNUC_CONST;
enum  {
	PEASY_APP_DUMMY_PROPERTY
};
PeasyApp* peasy_app_new (void);
PeasyApp* peasy_app_construct (GType object_type);
PeasyObject* peasy_object_new (void);
PeasyObject* peasy_object_construct (GType object_type);
static GObject * peasy_app_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void peasy_app_finalize (GObject* obj);
GType peasy_ui_widgets_get_type (void) G_GNUC_CONST;
enum  {
	PEASY_UI_WIDGETS_DUMMY_PROPERTY
};
PeasyUiWidgets* peasy_ui_widgets_new (void);
PeasyUiWidgets* peasy_ui_widgets_construct (GType object_type);
static void peasy_ui_widgets_finalize (GObject* obj);
GType peasy_data_get_type (void) G_GNUC_CONST;
enum  {
	PEASY_DATA_DUMMY_PROPERTY
};
static PeasyData* peasy_data_new (void);
static PeasyData* peasy_data_construct (GType object_type);
PeasyData* peasy_data_instance (void);
static void peasy_data_finalize (GObject* obj);


PeasyApp* peasy_app_construct (GType object_type) {
	PeasyApp * self = NULL;
	self = (PeasyApp*) peasy_object_construct (object_type);
	return self;
}


PeasyApp* peasy_app_new (void) {
	return peasy_app_construct (PEASY_TYPE_APP);
}


static GObject * peasy_app_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	PeasyApp * self;
	GeanyPlugin* _tmp0_ = NULL;
	GeanyData* _tmp1_ = NULL;
	GeanyApp* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GeanyPlugin* _tmp4_ = NULL;
	GeanyData* _tmp5_ = NULL;
	GeanyApp* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	GeanyPlugin* _tmp8_ = NULL;
	GeanyData* _tmp9_ = NULL;
	GeanyApp* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	GeanyPlugin* _tmp12_ = NULL;
	GeanyData* _tmp13_ = NULL;
	GeanyApp* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	parent_class = G_OBJECT_CLASS (peasy_app_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_APP, PeasyApp);
	_tmp0_ = peasy_peasy_plugin;
	_tmp1_ = _tmp0_->geany_data;
	_tmp2_ = _tmp1_->app;
	_tmp3_ = _tmp2_->debug_mode;
	self->debug_mode = _tmp3_;
	_tmp4_ = peasy_peasy_plugin;
	_tmp5_ = _tmp4_->geany_data;
	_tmp6_ = _tmp5_->app;
	_tmp7_ = _tmp6_->configdir;
	self->configdir = _tmp7_;
	_tmp8_ = peasy_peasy_plugin;
	_tmp9_ = _tmp8_->geany_data;
	_tmp10_ = _tmp9_->app;
	_tmp11_ = _tmp10_->datadir;
	self->datadir = _tmp11_;
	_tmp12_ = peasy_peasy_plugin;
	_tmp13_ = _tmp12_->geany_data;
	_tmp14_ = _tmp13_->app;
	_tmp15_ = _tmp14_->docdir;
	self->docdir = _tmp15_;
	return obj;
}


static void peasy_app_class_init (PeasyAppClass * klass) {
	peasy_app_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = peasy_app_constructor;
	G_OBJECT_CLASS (klass)->finalize = peasy_app_finalize;
}


static void peasy_app_instance_init (PeasyApp * self) {
}


static void peasy_app_finalize (GObject* obj) {
	PeasyApp * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_APP, PeasyApp);
	G_OBJECT_CLASS (peasy_app_parent_class)->finalize (obj);
}


GType peasy_app_get_type (void) {
	static volatile gsize peasy_app_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyApp), 0, (GInstanceInitFunc) peasy_app_instance_init, NULL };
		GType peasy_app_type_id;
		peasy_app_type_id = g_type_register_static (PEASY_TYPE_OBJECT, "PeasyApp", &g_define_type_info, 0);
		g_once_init_leave (&peasy_app_type_id__volatile, peasy_app_type_id);
	}
	return peasy_app_type_id__volatile;
}


PeasyUiWidgets* peasy_ui_widgets_construct (GType object_type) {
	PeasyUiWidgets * self = NULL;
	GeanyPlugin* _tmp0_ = NULL;
	GeanyData* _tmp1_ = NULL;
	GeanyMainWidgets* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	GeanyPlugin* _tmp4_ = NULL;
	GeanyData* _tmp5_ = NULL;
	GeanyMainWidgets* _tmp6_ = NULL;
	GtkWidget* _tmp7_ = NULL;
	GeanyPlugin* _tmp8_ = NULL;
	GeanyData* _tmp9_ = NULL;
	GeanyMainWidgets* _tmp10_ = NULL;
	GtkWidget* _tmp11_ = NULL;
	GeanyPlugin* _tmp12_ = NULL;
	GeanyData* _tmp13_ = NULL;
	GeanyMainWidgets* _tmp14_ = NULL;
	GtkWidget* _tmp15_ = NULL;
	GeanyPlugin* _tmp16_ = NULL;
	GeanyData* _tmp17_ = NULL;
	GeanyMainWidgets* _tmp18_ = NULL;
	GtkWidget* _tmp19_ = NULL;
	GeanyPlugin* _tmp20_ = NULL;
	GeanyData* _tmp21_ = NULL;
	GeanyMainWidgets* _tmp22_ = NULL;
	GtkWidget* _tmp23_ = NULL;
	GeanyPlugin* _tmp24_ = NULL;
	GeanyData* _tmp25_ = NULL;
	GeanyMainWidgets* _tmp26_ = NULL;
	GtkWidget* _tmp27_ = NULL;
	GeanyPlugin* _tmp28_ = NULL;
	GeanyData* _tmp29_ = NULL;
	GeanyMainWidgets* _tmp30_ = NULL;
	GtkWidget* _tmp31_ = NULL;
	GeanyPlugin* _tmp32_ = NULL;
	GeanyData* _tmp33_ = NULL;
	GeanyMainWidgets* _tmp34_ = NULL;
	GtkWidget* _tmp35_ = NULL;
	self = (PeasyUiWidgets*) peasy_object_construct (object_type);
	_tmp0_ = peasy_peasy_plugin;
	_tmp1_ = _tmp0_->geany_data;
	_tmp2_ = _tmp1_->main_widgets;
	_tmp3_ = _tmp2_->window;
	self->window = _tmp3_;
	_tmp4_ = peasy_peasy_plugin;
	_tmp5_ = _tmp4_->geany_data;
	_tmp6_ = _tmp5_->main_widgets;
	_tmp7_ = _tmp6_->toolbar;
	self->toolbar = _tmp7_;
	_tmp8_ = peasy_peasy_plugin;
	_tmp9_ = _tmp8_->geany_data;
	_tmp10_ = _tmp9_->main_widgets;
	_tmp11_ = _tmp10_->sidebar_notebook;
	self->sidebar_notebook = _tmp11_;
	_tmp12_ = peasy_peasy_plugin;
	_tmp13_ = _tmp12_->geany_data;
	_tmp14_ = _tmp13_->main_widgets;
	_tmp15_ = _tmp14_->notebook;
	self->notebook = _tmp15_;
	_tmp16_ = peasy_peasy_plugin;
	_tmp17_ = _tmp16_->geany_data;
	_tmp18_ = _tmp17_->main_widgets;
	_tmp19_ = _tmp18_->editor_menu;
	self->editor_menu = _tmp19_;
	_tmp20_ = peasy_peasy_plugin;
	_tmp21_ = _tmp20_->geany_data;
	_tmp22_ = _tmp21_->main_widgets;
	_tmp23_ = _tmp22_->tools_menu;
	self->tools_menu = _tmp23_;
	_tmp24_ = peasy_peasy_plugin;
	_tmp25_ = _tmp24_->geany_data;
	_tmp26_ = _tmp25_->main_widgets;
	_tmp27_ = _tmp26_->progressbar;
	self->progressbar = _tmp27_;
	_tmp28_ = peasy_peasy_plugin;
	_tmp29_ = _tmp28_->geany_data;
	_tmp30_ = _tmp29_->main_widgets;
	_tmp31_ = _tmp30_->message_window_notebook;
	self->message_window_notebook = _tmp31_;
	_tmp32_ = peasy_peasy_plugin;
	_tmp33_ = _tmp32_->geany_data;
	_tmp34_ = _tmp33_->main_widgets;
	_tmp35_ = _tmp34_->project_menu;
	self->project_menu = _tmp35_;
	return self;
}


PeasyUiWidgets* peasy_ui_widgets_new (void) {
	return peasy_ui_widgets_construct (PEASY_TYPE_UI_WIDGETS);
}


static void peasy_ui_widgets_class_init (PeasyUiWidgetsClass * klass) {
	peasy_ui_widgets_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = peasy_ui_widgets_finalize;
}


static void peasy_ui_widgets_instance_init (PeasyUiWidgets * self) {
}


static void peasy_ui_widgets_finalize (GObject* obj) {
	PeasyUiWidgets * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_UI_WIDGETS, PeasyUiWidgets);
	G_OBJECT_CLASS (peasy_ui_widgets_parent_class)->finalize (obj);
}


GType peasy_ui_widgets_get_type (void) {
	static volatile gsize peasy_ui_widgets_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_ui_widgets_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyUiWidgetsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_ui_widgets_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyUiWidgets), 0, (GInstanceInitFunc) peasy_ui_widgets_instance_init, NULL };
		GType peasy_ui_widgets_type_id;
		peasy_ui_widgets_type_id = g_type_register_static (PEASY_TYPE_OBJECT, "PeasyUiWidgets", &g_define_type_info, 0);
		g_once_init_leave (&peasy_ui_widgets_type_id__volatile, peasy_ui_widgets_type_id);
	}
	return peasy_ui_widgets_type_id__volatile;
}


static PeasyData* peasy_data_construct (GType object_type) {
	PeasyData * self = NULL;
	GeanyPlugin* _tmp0_ = NULL;
	GeanyData* _tmp1_ = NULL;
	GeanyPrefs* _tmp2_ = NULL;
	GeanyPlugin* _tmp3_ = NULL;
	GeanyData* _tmp4_ = NULL;
	GeanyInterfacePrefs* _tmp5_ = NULL;
	GeanyPlugin* _tmp6_ = NULL;
	GeanyData* _tmp7_ = NULL;
	GeanyToolPrefs* _tmp8_ = NULL;
	GeanyPlugin* _tmp9_ = NULL;
	GeanyData* _tmp10_ = NULL;
	GeanyToolbarPrefs* _tmp11_ = NULL;
	GeanyPlugin* _tmp12_ = NULL;
	GeanyData* _tmp13_ = NULL;
	GeanyEditorPrefs* _tmp14_ = NULL;
	GeanyPlugin* _tmp15_ = NULL;
	GeanyData* _tmp16_ = NULL;
	GeanyFilePrefs* _tmp17_ = NULL;
	GeanyPlugin* _tmp18_ = NULL;
	GeanyData* _tmp19_ = NULL;
	GeanySearchPrefs* _tmp20_ = NULL;
	GeanyPlugin* _tmp21_ = NULL;
	GeanyData* _tmp22_ = NULL;
	GeanyTemplatePrefs* _tmp23_ = NULL;
	GeanyPlugin* _tmp24_ = NULL;
	GeanyData* _tmp25_ = NULL;
	GeanyBuildInfo* _tmp26_ = NULL;
	PeasyApp* _tmp27_ = NULL;
	PeasyUiWidgets* _tmp28_ = NULL;
	self = (PeasyData*) peasy_object_construct (object_type);
	_tmp0_ = peasy_peasy_plugin;
	_tmp1_ = _tmp0_->geany_data;
	_tmp2_ = _tmp1_->prefs;
	self->prefs = _tmp2_;
	_tmp3_ = peasy_peasy_plugin;
	_tmp4_ = _tmp3_->geany_data;
	_tmp5_ = _tmp4_->interface_prefs;
	self->interface_prefs = _tmp5_;
	_tmp6_ = peasy_peasy_plugin;
	_tmp7_ = _tmp6_->geany_data;
	_tmp8_ = _tmp7_->tool_prefs;
	self->tool_prefs = _tmp8_;
	_tmp9_ = peasy_peasy_plugin;
	_tmp10_ = _tmp9_->geany_data;
	_tmp11_ = _tmp10_->toolbar_prefs;
	self->toolbar_prefs = _tmp11_;
	_tmp12_ = peasy_peasy_plugin;
	_tmp13_ = _tmp12_->geany_data;
	_tmp14_ = _tmp13_->editor_prefs;
	self->editor_prefs = _tmp14_;
	_tmp15_ = peasy_peasy_plugin;
	_tmp16_ = _tmp15_->geany_data;
	_tmp17_ = _tmp16_->file_prefs;
	self->file_prefs = _tmp17_;
	_tmp18_ = peasy_peasy_plugin;
	_tmp19_ = _tmp18_->geany_data;
	_tmp20_ = _tmp19_->search_prefs;
	self->search_prefs = _tmp20_;
	_tmp21_ = peasy_peasy_plugin;
	_tmp22_ = _tmp21_->geany_data;
	_tmp23_ = _tmp22_->template_prefs;
	self->template_prefs = _tmp23_;
	_tmp24_ = peasy_peasy_plugin;
	_tmp25_ = _tmp24_->geany_data;
	_tmp26_ = _tmp25_->build_info;
	self->build_info = _tmp26_;
	_tmp27_ = peasy_app_new ();
	_g_object_unref0 (self->app);
	self->app = _tmp27_;
	_tmp28_ = peasy_ui_widgets_new ();
	_g_object_unref0 (self->widgets);
	self->widgets = _tmp28_;
	return self;
}


static PeasyData* peasy_data_new (void) {
	return peasy_data_construct (PEASY_TYPE_DATA);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


PeasyData* peasy_data_instance (void) {
	PeasyData* result = NULL;
	PeasyData* _d = NULL;
	PeasyData* _tmp0_ = NULL;
	PeasyData* _tmp4_ = NULL;
	PeasyData* _tmp5_ = NULL;
	_tmp0_ = peasy_data__instance;
	if (_tmp0_ == NULL) {
		PeasyData* _tmp1_ = NULL;
		PeasyData* _tmp2_ = NULL;
		PeasyData* _tmp3_ = NULL;
		_tmp1_ = peasy_data_new ();
		_g_object_unref0 (_d);
		_d = _tmp1_;
		_tmp2_ = _d;
		_tmp3_ = _g_object_ref0 (_tmp2_);
		_g_object_unref0 (peasy_data__instance);
		peasy_data__instance = _tmp3_;
	}
	_tmp4_ = peasy_data__instance;
	_tmp5_ = _g_object_ref0 (_tmp4_);
	result = _tmp5_;
	_g_object_unref0 (_d);
	return result;
}


static void peasy_data_class_init (PeasyDataClass * klass) {
	peasy_data_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = peasy_data_finalize;
}


static void peasy_data_instance_init (PeasyData * self) {
}


static void peasy_data_finalize (GObject* obj) {
	PeasyData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_DATA, PeasyData);
	_g_object_unref0 (self->widgets);
	_g_object_unref0 (self->app);
	G_OBJECT_CLASS (peasy_data_parent_class)->finalize (obj);
}


GType peasy_data_get_type (void) {
	static volatile gsize peasy_data_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_data_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyDataClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_data_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyData), 0, (GInstanceInitFunc) peasy_data_instance_init, NULL };
		GType peasy_data_type_id;
		peasy_data_type_id = g_type_register_static (PEASY_TYPE_OBJECT, "PeasyData", &g_define_type_info, 0);
		g_once_init_leave (&peasy_data_type_id__volatile, peasy_data_type_id);
	}
	return peasy_data_type_id__volatile;
}



