/* editor.c generated by valac, the Vala compiler
 * generated from editor.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <geanyplugin.h>
#include <stdlib.h>
#include <string.h>


#define PEASY_TYPE_EDITOR (peasy_editor_get_type ())
#define PEASY_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_EDITOR, PeasyEditor))
#define PEASY_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_EDITOR, PeasyEditorClass))
#define PEASY_IS_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_EDITOR))
#define PEASY_IS_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_EDITOR))
#define PEASY_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_EDITOR, PeasyEditorClass))

typedef struct _PeasyEditor PeasyEditor;
typedef struct _PeasyEditorClass PeasyEditorClass;
typedef struct _PeasyEditorPrivate PeasyEditorPrivate;

#define PEASY_TYPE_OBJECT (peasy_object_get_type ())
#define PEASY_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_OBJECT, PeasyObject))
#define PEASY_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_OBJECT, PeasyObjectClass))
#define PEASY_IS_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_OBJECT))
#define PEASY_IS_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_OBJECT))
#define PEASY_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_OBJECT, PeasyObjectClass))

typedef struct _PeasyObject PeasyObject;
typedef struct _PeasyObjectClass PeasyObjectClass;

#define PEASY_TYPE_DOCUMENT (peasy_document_get_type ())
#define PEASY_DOCUMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_DOCUMENT, PeasyDocument))
#define PEASY_DOCUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_DOCUMENT, PeasyDocumentClass))
#define PEASY_IS_DOCUMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_DOCUMENT))
#define PEASY_IS_DOCUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_DOCUMENT))
#define PEASY_DOCUMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_DOCUMENT, PeasyDocumentClass))

typedef struct _PeasyDocument PeasyDocument;
typedef struct _PeasyDocumentClass PeasyDocumentClass;
typedef struct _PeasyObjectPrivate PeasyObjectPrivate;
typedef struct _PeasyDocumentPrivate PeasyDocumentPrivate;

struct _PeasyEditor {
	GObject parent_instance;
	PeasyEditorPrivate * priv;
	PeasyDocument* document;
	GeanyEditor* _editor;
};

struct _PeasyEditorClass {
	GObjectClass parent_class;
};

struct _PeasyObject {
	GObject parent_instance;
	PeasyObjectPrivate * priv;
};

struct _PeasyObjectClass {
	GObjectClass parent_class;
};

struct _PeasyDocument {
	PeasyObject parent_instance;
	PeasyDocumentPrivate * priv;
	PeasyEditor* editor;
	GeanyDocument* _doc;
};

struct _PeasyDocumentClass {
	PeasyObjectClass parent_class;
};


static gpointer peasy_editor_parent_class = NULL;

GType peasy_editor_get_type (void) G_GNUC_CONST;
GType peasy_object_get_type (void) G_GNUC_CONST;
GType peasy_document_get_type (void) G_GNUC_CONST;
enum  {
	PEASY_EDITOR_DUMMY_PROPERTY,
	PEASY_EDITOR_AUTO_INDENT,
	PEASY_EDITOR_INDENT_TYPE,
	PEASY_EDITOR_LINE_BREAKING
};
PeasyEditor* peasy_editor_new_create (PeasyDocument* doc);
PeasyEditor* peasy_editor_construct_create (GType object_type, PeasyDocument* doc);
gchar* peasy_editor_get_word_at (PeasyEditor* self, gint pos, const gchar* wordchars);
gboolean peasy_editor_goto (PeasyEditor* self, gint pos, gboolean mark);
void peasy_editor_indicator_clear (PeasyEditor* self, GeanyIndicator indic);
void peasy_editor_indicator_set_on_line (PeasyEditor* self, GeanyIndicator indic, gint line);
void peasy_editor_indicator_set_on_range (PeasyEditor* self, GeanyIndicator indic, gint start, gint end);
PeasyEditor* peasy_editor_new (void);
PeasyEditor* peasy_editor_construct (GType object_type);
gboolean peasy_editor_get_auto_indent (PeasyEditor* self);
GeanyIndentType peasy_editor_get_indent_type (PeasyEditor* self);
void peasy_editor_set_indent_type (PeasyEditor* self, GeanyIndentType value);
gboolean peasy_editor_get_line_breaking (PeasyEditor* self);
static void peasy_editor_finalize (GObject* obj);
static void _vala_peasy_editor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_peasy_editor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


PeasyEditor* peasy_editor_construct_create (GType object_type, PeasyDocument* doc) {
	PeasyEditor * self = NULL;
	PeasyDocument* _tmp0_ = NULL;
	GeanyDocument* _tmp1_ = NULL;
	GeanyEditor* _tmp2_ = NULL;
	PeasyDocument* _tmp3_ = NULL;
	g_return_val_if_fail (doc != NULL, NULL);
	self = (PeasyEditor*) g_object_new (object_type, NULL);
	_tmp0_ = doc;
	_tmp1_ = _tmp0_->_doc;
	_tmp2_ = _tmp1_->editor;
	self->_editor = _tmp2_;
	_tmp3_ = doc;
	self->document = _tmp3_;
	return self;
}


PeasyEditor* peasy_editor_new_create (PeasyDocument* doc) {
	return peasy_editor_construct_create (PEASY_TYPE_EDITOR, doc);
}


gchar* peasy_editor_get_word_at (PeasyEditor* self, gint pos, const gchar* wordchars) {
	gchar* result = NULL;
	GeanyEditor* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_editor;
	_tmp1_ = pos;
	_tmp2_ = wordchars;
	_tmp3_ = editor_get_word_at_pos (_tmp0_, _tmp1_, _tmp2_);
	result = _tmp3_;
	return result;
}


gboolean peasy_editor_goto (PeasyEditor* self, gint pos, gboolean mark) {
	gboolean result = FALSE;
	GeanyEditor* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->_editor;
	_tmp1_ = pos;
	_tmp2_ = mark;
	_tmp3_ = editor_goto_pos (_tmp0_, _tmp1_, _tmp2_);
	result = _tmp3_;
	return result;
}


void peasy_editor_indicator_clear (PeasyEditor* self, GeanyIndicator indic) {
	GeanyEditor* _tmp0_ = NULL;
	GeanyIndicator _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->_editor;
	_tmp1_ = indic;
	editor_indicator_clear (_tmp0_, (gint) _tmp1_);
}


void peasy_editor_indicator_set_on_line (PeasyEditor* self, GeanyIndicator indic, gint line) {
	GeanyEditor* _tmp0_ = NULL;
	GeanyIndicator _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->_editor;
	_tmp1_ = indic;
	_tmp2_ = line;
	editor_indicator_set_on_line (_tmp0_, (gint) _tmp1_, _tmp2_);
}


void peasy_editor_indicator_set_on_range (PeasyEditor* self, GeanyIndicator indic, gint start, gint end) {
	GeanyEditor* _tmp0_ = NULL;
	GeanyIndicator _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->_editor;
	_tmp1_ = indic;
	_tmp2_ = start;
	_tmp3_ = end;
	editor_indicator_set_on_range (_tmp0_, (gint) _tmp1_, _tmp2_, _tmp3_);
}


PeasyEditor* peasy_editor_construct (GType object_type) {
	PeasyEditor * self = NULL;
	self = (PeasyEditor*) g_object_new (object_type, NULL);
	return self;
}


PeasyEditor* peasy_editor_new (void) {
	return peasy_editor_construct (PEASY_TYPE_EDITOR);
}


gboolean peasy_editor_get_auto_indent (PeasyEditor* self) {
	gboolean result;
	GeanyEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->_editor;
	_tmp1_ = _tmp0_->auto_indent;
	result = _tmp1_;
	return result;
}


GeanyIndentType peasy_editor_get_indent_type (PeasyEditor* self) {
	GeanyIndentType result;
	GeanyEditor* _tmp0_ = NULL;
	GeanyIndentType _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->_editor;
	_tmp1_ = _tmp0_->indent_type;
	result = _tmp1_;
	return result;
}


void peasy_editor_set_indent_type (PeasyEditor* self, GeanyIndentType value) {
	GeanyEditor* _tmp0_ = NULL;
	GeanyIndentType _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->_editor;
	_tmp1_ = value;
	editor_set_indent_type (_tmp0_, _tmp1_);
	g_object_notify ((GObject *) self, "indent-type");
}


gboolean peasy_editor_get_line_breaking (PeasyEditor* self) {
	gboolean result;
	GeanyEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->_editor;
	_tmp1_ = _tmp0_->line_breaking;
	result = _tmp1_;
	return result;
}


static void peasy_editor_class_init (PeasyEditorClass * klass) {
	peasy_editor_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_peasy_editor_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_peasy_editor_set_property;
	G_OBJECT_CLASS (klass)->finalize = peasy_editor_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), PEASY_EDITOR_AUTO_INDENT, g_param_spec_boolean ("auto-indent", "auto-indent", "auto-indent", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), PEASY_EDITOR_INDENT_TYPE, g_param_spec_int ("indent-type", "indent-type", "indent-type", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), PEASY_EDITOR_LINE_BREAKING, g_param_spec_boolean ("line-breaking", "line-breaking", "line-breaking", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void peasy_editor_instance_init (PeasyEditor * self) {
}


static void peasy_editor_finalize (GObject* obj) {
	PeasyEditor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_EDITOR, PeasyEditor);
	G_OBJECT_CLASS (peasy_editor_parent_class)->finalize (obj);
}


GType peasy_editor_get_type (void) {
	static volatile gsize peasy_editor_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_editor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyEditorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_editor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyEditor), 0, (GInstanceInitFunc) peasy_editor_instance_init, NULL };
		GType peasy_editor_type_id;
		peasy_editor_type_id = g_type_register_static (G_TYPE_OBJECT, "PeasyEditor", &g_define_type_info, 0);
		g_once_init_leave (&peasy_editor_type_id__volatile, peasy_editor_type_id);
	}
	return peasy_editor_type_id__volatile;
}


static void _vala_peasy_editor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	PeasyEditor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PEASY_TYPE_EDITOR, PeasyEditor);
	switch (property_id) {
		case PEASY_EDITOR_AUTO_INDENT:
		g_value_set_boolean (value, peasy_editor_get_auto_indent (self));
		break;
		case PEASY_EDITOR_INDENT_TYPE:
		g_value_set_int (value, peasy_editor_get_indent_type (self));
		break;
		case PEASY_EDITOR_LINE_BREAKING:
		g_value_set_boolean (value, peasy_editor_get_line_breaking (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_peasy_editor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	PeasyEditor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PEASY_TYPE_EDITOR, PeasyEditor);
	switch (property_id) {
		case PEASY_EDITOR_INDENT_TYPE:
		peasy_editor_set_indent_type (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



