/* highlighting.c generated by valac, the Vala compiler
 * generated from highlighting.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <geanyplugin.h>
#include <string.h>

typedef struct _PeasyHighlighting PeasyHighlighting;

#define PEASY_TYPE_OBJECT (peasy_object_get_type ())
#define PEASY_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_OBJECT, PeasyObject))
#define PEASY_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_OBJECT, PeasyObjectClass))
#define PEASY_IS_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_OBJECT))
#define PEASY_IS_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_OBJECT))
#define PEASY_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_OBJECT, PeasyObjectClass))

typedef struct _PeasyObject PeasyObject;
typedef struct _PeasyObjectClass PeasyObjectClass;

#define PEASY_TYPE_FILETYPE (peasy_filetype_get_type ())
#define PEASY_FILETYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_FILETYPE, PeasyFiletype))
#define PEASY_FILETYPE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_FILETYPE, PeasyFiletypeClass))
#define PEASY_IS_FILETYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_FILETYPE))
#define PEASY_IS_FILETYPE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_FILETYPE))
#define PEASY_FILETYPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_FILETYPE, PeasyFiletypeClass))

typedef struct _PeasyFiletype PeasyFiletype;
typedef struct _PeasyFiletypeClass PeasyFiletypeClass;
typedef struct _PeasyObjectPrivate PeasyObjectPrivate;
typedef struct _PeasyFiletypePrivate PeasyFiletypePrivate;
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))

struct _PeasyHighlighting {
	int dummy;
};

struct _PeasyObject {
	GObject parent_instance;
	PeasyObjectPrivate * priv;
};

struct _PeasyObjectClass {
	GObjectClass parent_class;
};

struct _PeasyFiletype {
	PeasyObject parent_instance;
	PeasyFiletypePrivate * priv;
	GeanyFiletype* _ft;
};

struct _PeasyFiletypeClass {
	PeasyObjectClass parent_class;
};



void peasy_highlighting_free (PeasyHighlighting* self);
static void peasy_highlighting_instance_init (PeasyHighlighting * self);
gboolean peasy_highlighting_is_string_style (gint lexer, gint style);
gboolean peasy_highlighting_is_comment_style (gint lexer, gint style);
gboolean peasy_highlighting_is_code_style (gint lexer, gint style);
GType peasy_object_get_type (void) G_GNUC_CONST;
GType peasy_filetype_get_type (void) G_GNUC_CONST;
void peasy_highlighting_get_lexer_style (PeasyFiletype* ft, gint style, GeanyLexerStyle* result);
static GeanyLexerStyle* _geany_lexer_style_dup (GeanyLexerStyle* self);
static PeasyHighlighting* peasy_highlighting_new (void);
static PeasyHighlighting* peasy_highlighting_new (void);


gboolean peasy_highlighting_is_string_style (gint lexer, gint style) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	_tmp0_ = lexer;
	_tmp1_ = style;
	_tmp2_ = highlighting_is_string_style (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


gboolean peasy_highlighting_is_comment_style (gint lexer, gint style) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	_tmp0_ = lexer;
	_tmp1_ = style;
	_tmp2_ = highlighting_is_comment_style (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


gboolean peasy_highlighting_is_code_style (gint lexer, gint style) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	_tmp0_ = lexer;
	_tmp1_ = style;
	_tmp2_ = highlighting_is_code_style (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


static GeanyLexerStyle* _geany_lexer_style_dup (GeanyLexerStyle* self) {
	GeanyLexerStyle* dup;
	dup = g_new0 (GeanyLexerStyle, 1);
	memcpy (dup, self, sizeof (GeanyLexerStyle));
	return dup;
}


static gpointer __geany_lexer_style_dup0 (gpointer self) {
	return self ? _geany_lexer_style_dup (self) : NULL;
}


void peasy_highlighting_get_lexer_style (PeasyFiletype* ft, gint style, GeanyLexerStyle* result) {
	GeanyLexerStyle* ret = NULL;
	PeasyFiletype* _tmp0_ = NULL;
	GeanyFiletype* _tmp1_ = NULL;
	GeanyFiletypeID _tmp2_ = 0;
	gint _tmp3_ = 0;
	GeanyLexerStyle* _tmp4_ = NULL;
	GeanyLexerStyle* _tmp5_ = NULL;
	g_return_if_fail (ft != NULL);
	_tmp0_ = ft;
	_tmp1_ = _tmp0_->_ft;
	_tmp2_ = _tmp1_->id;
	_tmp3_ = style;
	_tmp4_ = highlighting_get_style ((gint) _tmp2_, _tmp3_);
	_tmp5_ = __geany_lexer_style_dup0 (_tmp4_);
	ret = _tmp5_;
	*result = (GeanyLexerStyle) (*ret);
	_g_free0 (ret);
	return;
}


static PeasyHighlighting* peasy_highlighting_new (void) {
	PeasyHighlighting* self;
	self = g_slice_new0 (PeasyHighlighting);
	peasy_highlighting_instance_init (self);
	return self;
}


static void peasy_highlighting_instance_init (PeasyHighlighting * self) {
}


void peasy_highlighting_free (PeasyHighlighting* self) {
	g_slice_free (PeasyHighlighting, self);
}



