/* plugin.c generated by valac, the Vala compiler
 * generated from plugin.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <geanyplugin.h>
#include <stdlib.h>
#include <string.h>


#define PEASY_TYPE_PLUGIN_CONFIGURE (peasy_plugin_configure_get_type ())
#define PEASY_PLUGIN_CONFIGURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_CONFIGURE, PeasyPluginConfigure))
#define PEASY_IS_PLUGIN_CONFIGURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_CONFIGURE))
#define PEASY_PLUGIN_CONFIGURE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_CONFIGURE, PeasyPluginConfigureIface))

typedef struct _PeasyPluginConfigure PeasyPluginConfigure;
typedef struct _PeasyPluginConfigureIface PeasyPluginConfigureIface;

#define PEASY_TYPE_PLUGIN_HELP (peasy_plugin_help_get_type ())
#define PEASY_PLUGIN_HELP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_HELP, PeasyPluginHelp))
#define PEASY_IS_PLUGIN_HELP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_HELP))
#define PEASY_PLUGIN_HELP_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_HELP, PeasyPluginHelpIface))

typedef struct _PeasyPluginHelp PeasyPluginHelp;
typedef struct _PeasyPluginHelpIface PeasyPluginHelpIface;

#define PEASY_TYPE_OBJECT (peasy_object_get_type ())
#define PEASY_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_OBJECT, PeasyObject))
#define PEASY_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_OBJECT, PeasyObjectClass))
#define PEASY_IS_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_OBJECT))
#define PEASY_IS_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_OBJECT))
#define PEASY_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_OBJECT, PeasyObjectClass))

typedef struct _PeasyObject PeasyObject;
typedef struct _PeasyObjectClass PeasyObjectClass;
typedef struct _PeasyObjectPrivate PeasyObjectPrivate;

#define PEASY_TYPE_PLUGIN_IFACE (peasy_plugin_iface_get_type ())
#define PEASY_PLUGIN_IFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN_IFACE, PeasyPluginIface))
#define PEASY_IS_PLUGIN_IFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN_IFACE))
#define PEASY_PLUGIN_IFACE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), PEASY_TYPE_PLUGIN_IFACE, PeasyPluginIfaceIface))

typedef struct _PeasyPluginIface PeasyPluginIface;
typedef struct _PeasyPluginIfaceIface PeasyPluginIfaceIface;

#define PEASY_TYPE_PLUGIN (peasy_plugin_get_type ())
#define PEASY_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PLUGIN, PeasyPlugin))
#define PEASY_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_PLUGIN, PeasyPluginClass))
#define PEASY_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PLUGIN))
#define PEASY_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_PLUGIN))
#define PEASY_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_PLUGIN, PeasyPluginClass))

typedef struct _PeasyPlugin PeasyPlugin;
typedef struct _PeasyPluginClass PeasyPluginClass;
typedef struct _PeasyPluginPrivate PeasyPluginPrivate;

#define PEASY_TYPE_DATA (peasy_data_get_type ())
#define PEASY_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_DATA, PeasyData))
#define PEASY_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_DATA, PeasyDataClass))
#define PEASY_IS_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_DATA))
#define PEASY_IS_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_DATA))
#define PEASY_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_DATA, PeasyDataClass))

typedef struct _PeasyData PeasyData;
typedef struct _PeasyDataClass PeasyDataClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define PEASY_TYPE_KEY_GROUP (peasy_key_group_get_type ())
#define PEASY_KEY_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_KEY_GROUP, PeasyKeyGroup))
#define PEASY_KEY_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_KEY_GROUP, PeasyKeyGroupClass))
#define PEASY_IS_KEY_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_KEY_GROUP))
#define PEASY_IS_KEY_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_KEY_GROUP))
#define PEASY_KEY_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_KEY_GROUP, PeasyKeyGroupClass))

typedef struct _PeasyKeyGroup PeasyKeyGroup;
typedef struct _PeasyKeyGroupClass PeasyKeyGroupClass;

#define PEASY_TYPE_PROJECT (peasy_project_get_type ())
#define PEASY_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_PROJECT, PeasyProject))
#define PEASY_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_PROJECT, PeasyProjectClass))
#define PEASY_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_PROJECT))
#define PEASY_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_PROJECT))
#define PEASY_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_PROJECT, PeasyProjectClass))

typedef struct _PeasyProject PeasyProject;
typedef struct _PeasyProjectClass PeasyProjectClass;

struct _PeasyPluginConfigureIface {
	GTypeInterface parent_iface;
	GtkWidget* (*configure) (PeasyPluginConfigure* self, GtkDialog* parent);
};

struct _PeasyPluginHelpIface {
	GTypeInterface parent_iface;
	void (*help) (PeasyPluginHelp* self);
};

struct _PeasyObject {
	GObject parent_instance;
	PeasyObjectPrivate * priv;
};

struct _PeasyObjectClass {
	GObjectClass parent_class;
};

struct _PeasyPluginIfaceIface {
	GTypeInterface parent_iface;
	GeanyPlugin* (*get_geany_plugin) (PeasyPluginIface* self);
	void (*set_geany_plugin) (PeasyPluginIface* self, GeanyPlugin* value);
};

struct _PeasyPlugin {
	PeasyObject parent_instance;
	PeasyPluginPrivate * priv;
	PeasyData* data;
};

struct _PeasyPluginClass {
	PeasyObjectClass parent_class;
	gboolean (*enable) (PeasyPlugin* self);
	void (*disable) (PeasyPlugin* self);
};

struct _PeasyPluginPrivate {
	GeanyPlugin* _geany_plugin;
};


static gpointer peasy_plugin_parent_class = NULL;
extern GeanyPlugin* peasy_peasy_plugin;
static PeasyPluginIfaceIface* peasy_plugin_peasy_plugin_iface_parent_iface = NULL;

GType peasy_plugin_configure_get_type (void) G_GNUC_CONST;
GtkWidget* peasy_plugin_configure_configure (PeasyPluginConfigure* self, GtkDialog* parent);
GType peasy_plugin_help_get_type (void) G_GNUC_CONST;
void peasy_plugin_help_help (PeasyPluginHelp* self);
GType peasy_object_get_type (void) G_GNUC_CONST;
GType peasy_plugin_iface_get_type (void) G_GNUC_CONST;
GType peasy_plugin_get_type (void) G_GNUC_CONST;
GType peasy_data_get_type (void) G_GNUC_CONST;
#define PEASY_PLUGIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), PEASY_TYPE_PLUGIN, PeasyPluginPrivate))
enum  {
	PEASY_PLUGIN_DUMMY_PROPERTY,
	PEASY_PLUGIN_GEANY_PLUGIN
};
PeasyData* peasy_data_instance (void);
gboolean peasy_plugin_enable (PeasyPlugin* self);
static gboolean peasy_plugin_real_enable (PeasyPlugin* self);
void peasy_plugin_disable (PeasyPlugin* self);
static void peasy_plugin_real_disable (PeasyPlugin* self);
static PeasyPlugin* peasy_plugin_construct (GType object_type);
PeasyObject* peasy_object_new (void);
PeasyObject* peasy_object_construct (GType object_type);
GType peasy_key_group_get_type (void) G_GNUC_CONST;
PeasyKeyGroup* peasy_plugin_add_key_group (PeasyPlugin* self, const gchar* section_name, gsize count);
GeanyPlugin* peasy_plugin_iface_get_geany_plugin (PeasyPluginIface* self);
PeasyKeyGroup* peasy_key_group_new_from_geany (GeanyKeyGroup* kb_group);
PeasyKeyGroup* peasy_key_group_construct_from_geany (GType object_type, GeanyKeyGroup* kb_group);
GType peasy_project_get_type (void) G_GNUC_CONST;
PeasyProject* peasy_plugin_get_project (PeasyPlugin* self);
PeasyProject* peasy_project_new_from_geany (GeanyProject* project);
PeasyProject* peasy_project_construct_from_geany (GType object_type, GeanyProject* project);
static void peasy_plugin_finalize (GObject* obj);
static void _vala_peasy_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
void peasy_plugin_iface_set_geany_plugin (PeasyPluginIface* self, GeanyPlugin* value);
static void _vala_peasy_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GtkWidget* peasy_plugin_configure_configure (PeasyPluginConfigure* self, GtkDialog* parent) {
	g_return_val_if_fail (self != NULL, NULL);
	return PEASY_PLUGIN_CONFIGURE_GET_INTERFACE (self)->configure (self, parent);
}


static void peasy_plugin_configure_base_init (PeasyPluginConfigureIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType peasy_plugin_configure_get_type (void) {
	static volatile gsize peasy_plugin_configure_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_configure_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginConfigureIface), (GBaseInitFunc) peasy_plugin_configure_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType peasy_plugin_configure_type_id;
		peasy_plugin_configure_type_id = g_type_register_static (G_TYPE_INTERFACE, "PeasyPluginConfigure", &g_define_type_info, 0);
		g_once_init_leave (&peasy_plugin_configure_type_id__volatile, peasy_plugin_configure_type_id);
	}
	return peasy_plugin_configure_type_id__volatile;
}


void peasy_plugin_help_help (PeasyPluginHelp* self) {
	g_return_if_fail (self != NULL);
	PEASY_PLUGIN_HELP_GET_INTERFACE (self)->help (self);
}


static void peasy_plugin_help_base_init (PeasyPluginHelpIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType peasy_plugin_help_get_type (void) {
	static volatile gsize peasy_plugin_help_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_help_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginHelpIface), (GBaseInitFunc) peasy_plugin_help_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType peasy_plugin_help_type_id;
		peasy_plugin_help_type_id = g_type_register_static (G_TYPE_INTERFACE, "PeasyPluginHelp", &g_define_type_info, 0);
		g_once_init_leave (&peasy_plugin_help_type_id__volatile, peasy_plugin_help_type_id);
	}
	return peasy_plugin_help_type_id__volatile;
}


static gboolean peasy_plugin_real_enable (PeasyPlugin* self) {
	g_critical ("Type `%s' does not implement abstract method `peasy_plugin_enable'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return FALSE;
}


gboolean peasy_plugin_enable (PeasyPlugin* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return PEASY_PLUGIN_GET_CLASS (self)->enable (self);
}


static void peasy_plugin_real_disable (PeasyPlugin* self) {
	g_critical ("Type `%s' does not implement abstract method `peasy_plugin_disable'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void peasy_plugin_disable (PeasyPlugin* self) {
	g_return_if_fail (self != NULL);
	PEASY_PLUGIN_GET_CLASS (self)->disable (self);
}


static PeasyPlugin* peasy_plugin_construct (GType object_type) {
	PeasyPlugin * self = NULL;
	self = (PeasyPlugin*) peasy_object_construct (object_type);
	return self;
}


PeasyKeyGroup* peasy_plugin_add_key_group (PeasyPlugin* self, const gchar* section_name, gsize count) {
	PeasyKeyGroup* result = NULL;
	GeanyKeyGroup* kb_group = NULL;
	GeanyPlugin* _tmp0_ = NULL;
	GeanyPlugin* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gsize _tmp3_ = 0UL;
	GeanyKeyGroup* _tmp4_ = NULL;
	PeasyKeyGroup* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (section_name != NULL, NULL);
	_tmp0_ = peasy_plugin_iface_get_geany_plugin ((PeasyPluginIface*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = section_name;
	_tmp3_ = count;
	_tmp4_ = plugin_set_key_group_full (_tmp1_, _tmp2_, _tmp3_, NULL, NULL, NULL);
	kb_group = _tmp4_;
	g_return_val_if_fail (kb_group != NULL, NULL);
	_tmp5_ = peasy_key_group_new_from_geany (kb_group);
	result = _tmp5_;
	return result;
}


PeasyProject* peasy_plugin_get_project (PeasyPlugin* self) {
	PeasyProject* result = NULL;
	GeanyPlugin* _tmp0_ = NULL;
	GeanyData* _tmp1_ = NULL;
	GeanyApp* _tmp2_ = NULL;
	GeanyProject* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = peasy_peasy_plugin;
	_tmp1_ = _tmp0_->geany_data;
	_tmp2_ = _tmp1_->app;
	_tmp3_ = _tmp2_->project;
	if (_tmp3_ != NULL) {
		GeanyPlugin* _tmp4_ = NULL;
		GeanyData* _tmp5_ = NULL;
		GeanyApp* _tmp6_ = NULL;
		GeanyProject* _tmp7_ = NULL;
		PeasyProject* _tmp8_ = NULL;
		_tmp4_ = peasy_peasy_plugin;
		_tmp5_ = _tmp4_->geany_data;
		_tmp6_ = _tmp5_->app;
		_tmp7_ = _tmp6_->project;
		_tmp8_ = peasy_project_new_from_geany (_tmp7_);
		result = _tmp8_;
		return result;
	}
	result = NULL;
	return result;
}


static GeanyPlugin* peasy_plugin_real_get_geany_plugin (PeasyPluginIface* base) {
	GeanyPlugin* result;
	PeasyPlugin* self;
	GeanyPlugin* _tmp0_ = NULL;
	self = (PeasyPlugin*) base;
	_tmp0_ = self->priv->_geany_plugin;
	result = _tmp0_;
	return result;
}


static void peasy_plugin_real_set_geany_plugin (PeasyPluginIface* base, GeanyPlugin* value) {
	PeasyPlugin* self;
	GeanyPlugin* _tmp0_ = NULL;
	self = (PeasyPlugin*) base;
	_tmp0_ = value;
	self->priv->_geany_plugin = _tmp0_;
	g_object_notify ((GObject *) self, "geany-plugin");
}


static void peasy_plugin_class_init (PeasyPluginClass * klass) {
	peasy_plugin_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PeasyPluginPrivate));
	((PeasyPluginClass *) klass)->enable = peasy_plugin_real_enable;
	((PeasyPluginClass *) klass)->disable = peasy_plugin_real_disable;
	G_OBJECT_CLASS (klass)->get_property = _vala_peasy_plugin_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_peasy_plugin_set_property;
	G_OBJECT_CLASS (klass)->finalize = peasy_plugin_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), PEASY_PLUGIN_GEANY_PLUGIN, g_param_spec_pointer ("geany-plugin", "geany-plugin", "geany-plugin", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
}


static void peasy_plugin_peasy_plugin_iface_interface_init (PeasyPluginIfaceIface * iface) {
	peasy_plugin_peasy_plugin_iface_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_geany_plugin = peasy_plugin_real_get_geany_plugin;
	iface->set_geany_plugin = peasy_plugin_real_set_geany_plugin;
}


static void peasy_plugin_instance_init (PeasyPlugin * self) {
	PeasyData* _tmp0_ = NULL;
	self->priv = PEASY_PLUGIN_GET_PRIVATE (self);
	_tmp0_ = peasy_data_instance ();
	self->data = _tmp0_;
}


static void peasy_plugin_finalize (GObject* obj) {
	PeasyPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PEASY_TYPE_PLUGIN, PeasyPlugin);
	_g_object_unref0 (self->data);
	G_OBJECT_CLASS (peasy_plugin_parent_class)->finalize (obj);
}


GType peasy_plugin_get_type (void) {
	static volatile gsize peasy_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyPlugin), 0, (GInstanceInitFunc) peasy_plugin_instance_init, NULL };
		static const GInterfaceInfo peasy_plugin_iface_info = { (GInterfaceInitFunc) peasy_plugin_peasy_plugin_iface_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType peasy_plugin_type_id;
		peasy_plugin_type_id = g_type_register_static (PEASY_TYPE_OBJECT, "PeasyPlugin", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_type_add_interface_static (peasy_plugin_type_id, PEASY_TYPE_PLUGIN_IFACE, &peasy_plugin_iface_info);
		g_once_init_leave (&peasy_plugin_type_id__volatile, peasy_plugin_type_id);
	}
	return peasy_plugin_type_id__volatile;
}


static void _vala_peasy_plugin_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	PeasyPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PEASY_TYPE_PLUGIN, PeasyPlugin);
	switch (property_id) {
		case PEASY_PLUGIN_GEANY_PLUGIN:
		g_value_set_pointer (value, peasy_plugin_iface_get_geany_plugin ((PeasyPluginIface*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_peasy_plugin_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	PeasyPlugin * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PEASY_TYPE_PLUGIN, PeasyPlugin);
	switch (property_id) {
		case PEASY_PLUGIN_GEANY_PLUGIN:
		peasy_plugin_iface_set_geany_plugin ((PeasyPluginIface*) self, g_value_get_pointer (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


GeanyPlugin* peasy_plugin_iface_get_geany_plugin (PeasyPluginIface* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return PEASY_PLUGIN_IFACE_GET_INTERFACE (self)->get_geany_plugin (self);
}


void peasy_plugin_iface_set_geany_plugin (PeasyPluginIface* self, GeanyPlugin* value) {
	g_return_if_fail (self != NULL);
	PEASY_PLUGIN_IFACE_GET_INTERFACE (self)->set_geany_plugin (self, value);
}


static void peasy_plugin_iface_base_init (PeasyPluginIfaceIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_object_interface_install_property (iface, g_param_spec_pointer ("geany-plugin", "geany-plugin", "geany-plugin", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	}
}


GType peasy_plugin_iface_get_type (void) {
	static volatile gsize peasy_plugin_iface_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_plugin_iface_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyPluginIfaceIface), (GBaseInitFunc) peasy_plugin_iface_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType peasy_plugin_iface_type_id;
		peasy_plugin_iface_type_id = g_type_register_static (G_TYPE_INTERFACE, "PeasyPluginIface", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (peasy_plugin_iface_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&peasy_plugin_iface_type_id__volatile, peasy_plugin_iface_type_id);
	}
	return peasy_plugin_iface_type_id__volatile;
}



