/* utils.c generated by valac, the Vala compiler
 * generated from utils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <geanyplugin.h>


#define PEASY_TYPE_UI_UTILS (peasy_ui_utils_get_type ())
#define PEASY_UI_UTILS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PEASY_TYPE_UI_UTILS, PeasyUiUtils))
#define PEASY_UI_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PEASY_TYPE_UI_UTILS, PeasyUiUtilsClass))
#define PEASY_IS_UI_UTILS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PEASY_TYPE_UI_UTILS))
#define PEASY_IS_UI_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PEASY_TYPE_UI_UTILS))
#define PEASY_UI_UTILS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PEASY_TYPE_UI_UTILS, PeasyUiUtilsClass))

typedef struct _PeasyUiUtils PeasyUiUtils;
typedef struct _PeasyUiUtilsClass PeasyUiUtilsClass;
typedef struct _PeasyUiUtilsPrivate PeasyUiUtilsPrivate;

struct _PeasyUiUtils {
	GObject parent_instance;
	PeasyUiUtilsPrivate * priv;
};

struct _PeasyUiUtilsClass {
	GObjectClass parent_class;
};


static gpointer peasy_ui_utils_parent_class = NULL;

GType peasy_ui_utils_get_type (void) G_GNUC_CONST;
enum  {
	PEASY_UI_UTILS_DUMMY_PROPERTY
};
GtkWidget* peasy_ui_utils_button_new_with_image (const gchar* stock_id, const gchar* text);
GtkWidget* peasy_ui_utils_image_menu_item_new (const gchar* stock_id, const gchar* label);
GtkWidget* peasy_ui_utils_path_box_new (const gchar* title, GtkFileChooserAction action, GtkEntry* entry);
GtkWidget* peasy_ui_utils_dialog_vbox_new (GtkDialog* dialog);
void peasy_ui_utils_add_document_sensitive (GtkWidget* widget);
GtkWidget* peasy_ui_utils_lookup_widget (PeasyUiUtils* self, GtkWidget* widget, const gchar* widget_name);
PeasyUiUtils* peasy_ui_utils_new (void);
PeasyUiUtils* peasy_ui_utils_construct (GType object_type);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GtkWidget* peasy_ui_utils_button_new_with_image (const gchar* stock_id, const gchar* text) {
	GtkWidget* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	g_return_val_if_fail (stock_id != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	_tmp0_ = stock_id;
	_tmp1_ = text;
	_tmp2_ = ui_button_new_with_image (_tmp0_, _tmp1_);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GtkWidget* peasy_ui_utils_image_menu_item_new (const gchar* stock_id, const gchar* label) {
	GtkWidget* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	g_return_val_if_fail (stock_id != NULL, NULL);
	g_return_val_if_fail (label != NULL, NULL);
	_tmp0_ = stock_id;
	_tmp1_ = label;
	_tmp2_ = ui_image_menu_item_new (_tmp0_, _tmp1_);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GtkWidget* peasy_ui_utils_path_box_new (const gchar* title, GtkFileChooserAction action, GtkEntry* entry) {
	GtkWidget* result = NULL;
	const gchar* _tmp0_ = NULL;
	GtkFileChooserAction _tmp1_ = 0;
	GtkEntry* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	GtkWidget* _tmp4_ = NULL;
	g_return_val_if_fail (entry != NULL, NULL);
	_tmp0_ = title;
	_tmp1_ = action;
	_tmp2_ = entry;
	_tmp3_ = ui_path_box_new (_tmp0_, _tmp1_, _tmp2_);
	_tmp4_ = _g_object_ref0 (_tmp3_);
	result = _tmp4_;
	return result;
}


GtkWidget* peasy_ui_utils_dialog_vbox_new (GtkDialog* dialog) {
	GtkWidget* result = NULL;
	GtkDialog* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	g_return_val_if_fail (dialog != NULL, NULL);
	_tmp0_ = dialog;
	_tmp1_ = ui_dialog_vbox_new (_tmp0_);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	result = _tmp2_;
	return result;
}


void peasy_ui_utils_add_document_sensitive (GtkWidget* widget) {
	GtkWidget* _tmp0_ = NULL;
	g_return_if_fail (widget != NULL);
	_tmp0_ = widget;
	ui_add_document_sensitive (_tmp0_);
}


GtkWidget* peasy_ui_utils_lookup_widget (PeasyUiUtils* self, GtkWidget* widget, const gchar* widget_name) {
	GtkWidget* result = NULL;
	GtkWidget* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (widget != NULL, NULL);
	g_return_val_if_fail (widget_name != NULL, NULL);
	_tmp0_ = widget;
	_tmp1_ = widget_name;
	_tmp2_ = ui_lookup_widget (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


PeasyUiUtils* peasy_ui_utils_construct (GType object_type) {
	PeasyUiUtils * self = NULL;
	self = (PeasyUiUtils*) g_object_new (object_type, NULL);
	return self;
}


PeasyUiUtils* peasy_ui_utils_new (void) {
	return peasy_ui_utils_construct (PEASY_TYPE_UI_UTILS);
}


static void peasy_ui_utils_class_init (PeasyUiUtilsClass * klass) {
	peasy_ui_utils_parent_class = g_type_class_peek_parent (klass);
}


static void peasy_ui_utils_instance_init (PeasyUiUtils * self) {
}


GType peasy_ui_utils_get_type (void) {
	static volatile gsize peasy_ui_utils_type_id__volatile = 0;
	if (g_once_init_enter (&peasy_ui_utils_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PeasyUiUtilsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) peasy_ui_utils_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PeasyUiUtils), 0, (GInstanceInitFunc) peasy_ui_utils_instance_init, NULL };
		GType peasy_ui_utils_type_id;
		peasy_ui_utils_type_id = g_type_register_static (G_TYPE_OBJECT, "PeasyUiUtils", &g_define_type_info, 0);
		g_once_init_leave (&peasy_ui_utils_type_id__volatile, peasy_ui_utils_type_id);
	}
	return peasy_ui_utils_type_id__volatile;
}



